[BE] 모임 인원 제한 추가
woowacourse-teams/2022-momo pull request #125
Opened 2022-07-28 07:56 UTC by Seongwon97

Issue #114 
#  🌟 구현할 기능
모임 정보에 최대 인원 정보를 추가한다.

# 🛠 상세 작업 
- [x] 모임 도메인에 최대 인원 정보를 추가
- [x] 참여자 수가 최대인원과 같을 시 참여 신청이 불가능하도록 구현 (모집 마감을 한다.)
- [x] 모임 도메인이 갖는 필드를 host의 ID에서 Member객체를 갖도록 수정
- [x] 모임 생성시 호스트가 참가자가 되도록 로직 수정

# ⏰ 예상 소요 시간
2일

---
close #114

2022-07-28 08:31 UTC, sinb57 requested changes

2022-07-28 08:31 UTC, sinb57 commented on backend/src/test/java/com/woowacourse/momo/acceptance/participant/ParticipantAcceptanceTest.java
> +    }
```suggestion
    void participateFullGroup() {
        String accessToken = MOMO.로_로그인한다();
        모임에_참여한다(accessToken, groupId).statusCode(HttpStatus.OK.value());

        accessToken = GUGU.로_로그인한다();
        모임에_참여한다(accessToken, groupId).statusCode(HttpStatus.BAD_REQUEST.value());
    }
```
첫번째 요청은 정상적으로 OK가 됐는지 확인하면, 시나리오가 보다 명확해보여요!!

2022-07-28 08:31 UTC, nbalance97 approved these changes
렉스 고생했어요~~~~ 한번 확인해주시고 반영해주세요!

2022-07-28 08:31 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
> +                    return GroupResponseAssembler.groupSummaryResponse(group, group.getHost());
`group -> GroupResponseAssembler.groupSummaryResponse(group, group.getHost())`

2022-07-28 08:31 UTC, nbalance97 commented on backend/src/test/java/com/woowacourse/momo/participant/controller/ParticipantControllerTest.java
> +    void participateParticipant() throws Exception {
reparticipate는 어떨까요?ㅎㅎ

2022-07-28 08:31 UTC, nbalance97 commented on backend/src/test/java/com/woowacourse/momo/participant/controller/ParticipantControllerTest.java
> +    Long saveGroupWithSetcapacity(Long hostId, int capacity) {
`saveGroupWithSetCapacity` 는 어떨까요?

2022-07-28 08:31 UTC, nbalance97 commented on backend/src/test/java/com/woowacourse/momo/participant/service/ParticipantServiceTest.java
> +    private Group saveGroupWithSetcapacity(int capacity) {
이전 리뷰랑 같습니다~

2022-07-28 08:31 UTC, nbalance97 commented on backend/src/test/java/com/woowacourse/momo/group/domain/group/GroupTest.java
> +    private Group constructGroupWithSetcapacity(int capacity) {
😱

2022-07-28 08:31 UTC, nbalance97 commented on backend/src/test/java/com/woowacourse/momo/group/domain/group/GroupTest.java
> +    void validateOvercapacity() {
😱

2022-07-28 08:55 UTC, kyukong reviewed
오랜만에 코딩하느라 수고 많으셨습니다!
한동안 코드를 안봐서 코드를 파악하기도 시간이 걸렸을텐데 고생하셨어요
리뷰 몇개 남겼으니 참고해주세요ㅎㅎ

2022-07-28 08:55 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> +    private int capacity;
용어가 마음에 드네요👍

2022-07-28 08:55 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> +    @JoinColumn(name = "host_id")
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn
```
@JoinColumn 을 사용한 엔티티에서 가지는 컬럼이라면 name 은 생략해도 됩니다 😊
그리고 @ManyToOne 의 기본 fetch 전략은 EAGER 이므로 LAZY 로 바꾸어주면 좋겠습니다~!ㅎㅎ

2022-07-28 08:55 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> +        this.capacity = capacity;
그룹 정보를 수정할 때도 capacity 검증 부탁드려요!

2022-07-28 08:55 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> +        return this.host.equals(host);
👍

2022-07-28 08:55 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> +    private void validateOvercapacity() {
```suggestion
    private void validateOverCapacity() {
```

2022-07-28 08:55 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> +            this.capacity = capacity;
capacity 를 값객체로 분리하여 검증 로직을 더 추가하면 좋을것같아요ㅎㅎ

- 음수 예외 처리
- 99명 이상일 경우 예외 처리

2022-07-28 08:55 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
> +        return GroupResponseAssembler.groupResponse(group, group.getHost());
GroupResponseAssembler.groupResponse 가 Group 과 Member 를 각각 받아서 직접 꺼낸 후 건내준거같은데 groupResponse 를 Group 만 받고 내부에서 Member 를 꺼내쓰도록 수정해도 좋을 것 같아요. 보니까 테스트코드와 여기에서밖에 안쓰여서요!

2022-07-28 08:55 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
> +                    return GroupResponseAssembler.groupSummaryResponse(group, group.getHost());
여기도 마찬가지로 Member 를 내부로 보내도 될것같습니다!

2022-07-28 08:55 UTC, kyukong commented on backend/src/test/java/com/woowacourse/momo/group/domain/group/GroupTest.java
> +    @DisplayName("회원이 모임의 생성자면 True를 반환한다.")
```suggestion
    @DisplayName("모임의 주최자일 경우 True 를 반환한다")
```
🥲

2022-07-28 13:37 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> +    @JoinColumn(name = "host_id")
`@JoinColumn`의 name내용은 제거하였습니다!! 
다만 host 연관관계의 fetch전략의 경우 참여하기를 제외한 Group관련 모든 기능들이 Host의 정보를 필요로 하기에 Lazy보다 Eager로 설정하는 것이 성능상에서 더 이점이 있지 않을까?하는 생각이 들어 fetch전략의 변경은 보류했습니다!
내일 한번 이야기해봐요😁

2022-07-29 04:17 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> +        this.capacity = capacity;
검증 로직을 추가했습니다!! 비밀번호를 수정할 때도 검증하도록 했습니다👍

2022-07-29 04:18 UTC, Seongwon97 commented on backend/src/test/resources/init.sql
> +    capacity integer      not null,
전반적으로 Sql파일들을 재정렬했습니다!

2022-07-29 04:19 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/service/dto/request/GroupRequest.java
> +    private int capacity;
ID의 경우 코드 전반적으로 Wrapper Class로, 그 외의 값의 경우 Request DTO에서만 Wrapper, 내부 비즈니스와 Response에서는 Primitive type으로 통일! 괜찮으신가요?

2022-07-29 04:19 UTC, Seongwon97 commented on backend/src/test/java/com/woowacourse/momo/acceptance/participant/ParticipantAcceptanceTest.java
> +    }
해당 내용도 반영했습니다!!

2022-07-29 04:20 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
> +                    return GroupResponseAssembler.groupSummaryResponse(group, group.getHost());
피드백을 반영하여 축약했습니다~

2022-07-29 04:20 UTC, Seongwon97 commented on backend/src/test/java/com/woowacourse/momo/participant/controller/ParticipantControllerTest.java
> +    void participateParticipant() throws Exception {
reparticipate이 영단어로 할 때는 Re-Participate인지 인텔리제이에서 계속 경고문을 줘서 reParticipate로 수정했습니다

2022-07-29 04:21 UTC, Seongwon97 commented on backend/src/test/java/com/woowacourse/momo/participant/controller/ParticipantControllerTest.java
> +    Long saveGroupWithSetcapacity(Long hostId, int capacity) {
아래의 피드백들 내용들 모두 카멜케이스로 올바르게 적용했습니다!

2022-07-29 04:21 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> +        this.capacity = capacity;
검증 로직을 추가했습니다👍

2022-07-29 04:22 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> +            this.capacity = capacity;
값 객체는 다른 값들도 VO로 분리한 것이 없어서 적용하지는 않았고 일단 예외 처리는 추가했습니다!!

2022-07-29 04:23 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
> +        return GroupResponseAssembler.groupResponse(group, group.getHost());
아래의 내용들 모두 불필요한 매개변수를 제거하였습니다👍

2022-07-29 04:24 UTC, Seongwon97 commented
리뷰를 반영했습니다~~😁

2022-07-29 04:25 UTC, nbalance97 approved these changes
변경사항 확인했습니다! 고생하셨습니다~

2022-07-29 05:05 UTC, sinb57 reviewed
수정된 코드 잘봤어요!! 몇가지 제안드린부분 확인해보시고, 답변 남겨주시면 확인한 후 approve 할게염

2022-07-29 05:05 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> +        if (1 > capacity || capacity > 99) {
매직넘버 처리해줄까요?? 예전에 했던 방식인데, 이렇게 해보는건 어때요???
https://github.com/sinb57/java-lotto/blob/sinb57/src/main/java/lotto/utils/BallNumberRange.java

2022-07-29 05:05 UTC, sinb57 commented on backend/src/test/java/com/woowacourse/momo/group/domain/group/GroupTest.java
> +    void validateCapacity(int capacity) {
에러 테스트 뿐만 아니라 정상 테스트도 확인해볼까요?

2022-07-29 05:11 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> +        if (1 > capacity || capacity > 99) {
변경해봤습니다~~👍👍👍👍

2022-07-29 05:21 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/service/dto/request/GroupRequest.java
> +    private int capacity;
좋아요~!!

2022-07-29 05:22 UTC, sinb57 approved these changes

2022-07-29 05:39 UTC, merged