[BE] 모임 모집 마감 로직 및 검증 로직 추가
woowacourse-teams/2022-momo pull request #145
Opened 2022-07-31 16:01 UTC by Seongwon97

Issue #135 

#  🌟 구현할 기능
모임 모집 마감 여부를 판단하는 로직 추가 및 필요한 메서드에 적용

# 🛠 상세 작업 
- [x] 모임 모집 마감 여부를 판단하는 로직 추가
   - [x] 마감 기한이 지났는가? → 로직으로 관리
   - [x] 최대 인원이 찼는가? → 로직으로 관리
   - 조기 종료 되었는가? → 데이터베이스에 저장 (해당 기능은 다음 이슈에서..🌟)
- [x] 모임 생성의 안정성을 주는 로직 추가
   - [x] Deadline은 현재 시간 이전이면 예외가 발생
   - [x] Deadline이 Duration 시작일 이후면 예외 발생
   - [x] 과거의 날짜로 모임 생성시 예외가 발생하도록 로직 추가
      - 모임 생성, 업데이트를 할 때의 request에서는 정적 팩토리 메서드로 검증 후 생성
- [x] Test Fixture를 현재 시간 기준으로 1일후, 3일후, 7일후로 변경
- [x] 모집 마감시 참여 신청을 못하도록 로직 수정
- [x] 모집 마감시 모임 삭제할 수 없도록 로직 수정
- [ ] 참여자가 있으면 삭제할 수 없도록....???
- [x] API스펙에 따라 모임 조회시 반환값에 finished 필드 추가

Close #135

2022-07-31 16:08 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/duration/Duration.java
> +    }
그룹을 새로 생성 및 업데이트시에 Duration의 값들이 현재 시간 이전인지 체크하는 로직이 없어서 추가를 하며, 그룹 생성 및 업데이트 요청에서 검증을 함께하는 생성자를 만들기 위해 정적 팩터리 메서드를 만들어 봤습니다. 

현재 이름이 떠오르지 않아 newDuration이라는 이름을 줬는데..변경해야할 것 같아요..추천 부탁드립니다😭

2022-07-31 16:08 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/duration/Duration.java
> +            throw new InvalidDurationException("시작일과 종료일은 과거의 날짜가 될 수 없습니다.");
해당 로직은 다른 검증에 마감시간은 시작시간 이전이어야 한다는 로직이 있어 시작일만 현재 날짜 이전인지 체크만 하면 되는데 상황별 명확한 에러메시지 출력을 위해 두개의 시간 모두 검증을 하도록 하였습니다.

2022-08-01 02:03 UTC, sinb57 reviewed
렉스!! 주말에도 고생많으셨어요~ 몇가지 리뷰남겼으니 확인부탁드려요~~

2022-08-01 02:03 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
>      }
`isFullCapacity`라는 명칭은 어떤가요? Over라는 단어에서 `capacity < paticipants.size()` 초과되었다는 의미가 느껴져요

2022-08-01 04:43 UTC, nbalance97 requested changes
렉스 안녕하세요~ 고생하셨습니다! 

개인적인 의견 남겼습니다ㅎㅎ 🥹

2022-08-01 04:43 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/duration/Duration.java
> +    }
정적 팩터리 메서드로 빼신 이유가 궁금합니다~ 아래에 있는 `validateEndIsNotBeforeStart` 또한 사용되지 않고 있네요.

2022-08-01 04:43 UTC, nbalance97 commented on backend/src/test/java/com/woowacourse/momo/fixture/GroupFixture.java
> +            _1일_후_23시_59분, "잠실역 스타벅스", "두두가 쏘는 커피~ 선착순 1명!!");
개인적으로 이전 코드와 변경사항을 비교해 보았을 때 가독성이 조금 떨어진 것 같아요 🤔

2022-08-01 04:44 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/duration/Duration.java
> +    }
오래된 데이터가 일반 생성자로 생성되면 예외가 발생하지 않을까?하는 생각에 정적 팩터리 메서드로 분리를 하였는데 그러한 데이터는 JPA에서 리플렉션을 통해 생성하기에 문제될게 없었더군요! 생성자에서 처리하도록 수정하겠습니다!

2022-08-01 04:57 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/duration/Duration.java
> +    }
오래된 데이터가 일반 생성자로 생성되면 예외가 발생하지 않을까?하는 생각에 정적 팩터리 메서드로 분리를 하였는데 그러한 데이터는 JPA에서 리플렉션을 통해 생성하기에 문제될게 없었더군요! 생성자에서 처리하도록 수정하겠습니다!

2022-08-01 05:00 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
>      }
`isFullCapacity`도 좋은 이름이네요!! 수정했습니다👍👍👍

2022-08-01 05:13 UTC, Seongwon97 commented on backend/src/test/java/com/woowacourse/momo/fixture/DurationFixture.java
> +    _3일_후부터_3일_후까지(_3일_후, _3일_후),
이름을 수정하니까 더 괜찮아진 것 같네요! `이틀후_하루동안`이라는 이름도 반영했습니다!

2022-08-01 05:13 UTC, Seongwon97 commented on backend/src/test/java/com/woowacourse/momo/fixture/GroupFixture.java
> +            _1일_후_23시_59분, "잠실역 스타벅스", "두두가 쏘는 커피~ 선착순 1명!!");
네이밍을 한번 수정해봤어요!! 이전보다는 나름..?가독성이 좋아진 것 같아요

2022-08-01 05:17 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/duration/Duration.java
> +    }
`LocalDateTime`을 `LocalDate`로 변경하기 위해 사용한 클래스였는데 `LocalDate.from()`으로도 변경할 수 있었네요! 해당 클래스 사용을 제거했습니다👍

2022-08-01 07:13 UTC, kyukong approved these changes
다른 분들이 꼼꼼하게 리뷰해주셔서 저는 딱히 남길게 없네요ㅎㅎ
수고하셨습니다!

2022-08-01 07:50 UTC, nbalance97 approved these changes

2022-08-01 08:57 UTC, merged