[BE] 페이지네이션 구현
woowacourse-teams/2022-momo pull request #152
Opened 2022-08-01 05:57 UTC by nbalance97

issue #132

2022-08-01 07:16 UTC, Seongwon97 requested changes
궁금한 내용과 사소하게 수정하면 좋겠는 내용들을 남겨봤어요!!
확인부탁드립니다😁

2022-08-01 07:16 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/controller/GroupController.java
> +        return ResponseEntity.ok(groupService.findAll(pageable));
12를 상수로 빼는게 좋은 방법인지는 모르지만 문법적으로 뺄 수 있는지 궁금해요
문법적으로 뺄 수 있나요..?

2022-08-01 07:16 UTC, Seongwon97 commented on backend/src/test/java/com/woowacourse/momo/acceptance/group/GroupRestHandler.java
> +    }
테스트의 확장성을 위해 페이지 넘버는 매개변수로 받게 하는 것도 좋을 것 같습니다!

2022-08-01 07:16 UTC, Seongwon97 commented on backend/src/test/java/com/woowacourse/momo/group/controller/GroupControllerTest.java
> +    @Test
```suggestion
    @DisplayName("그룹 목록을 페이지네이션 하여 가져온 결과를 출력한다")
    @Test
```

2022-08-01 07:16 UTC, Seongwon97 commented on backend/src/test/java/com/woowacourse/momo/group/service/GroupServiceTest.java
> +    @DisplayName("모임 목록중 두번째 페이지를 조회한다.")
```suggestion
    @DisplayName("모임 목록중 두번째 페이지를 조회한다")
```

2022-08-01 07:39 UTC, kyukong approved these changes
코드가 전체적으로 깔끔하고 좋네요
approve 할게요~!

2022-08-01 07:39 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/controller/GroupController.java
> +    public ResponseEntity<GroupPageResponse> findAll(@PageableDefault(size=12) Pageable pageable) {
페이징처리 할 때 결과값을 `12` 개로 정하는 것은 모모 서비스 비즈니스 로직이므로 service 로 옮기는 것은 어떨까요?

2022-08-01 08:29 UTC, nbalance97 commented on backend/src/test/java/com/woowacourse/momo/acceptance/group/GroupRestHandler.java
> +    }
페이지 넘버를 매개변수로 받게 하도록 변경하였습니다ㅎㅎ 감사합니다~

2022-08-01 10:52 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/group/controller/GroupController.java
> +        return ResponseEntity.ok(groupService.findAll(pageable));
아래 유콩의 리뷰랑 합쳐서 Service단에서 페이지 크기를 지정하도록 변경하였습니다ㅎㅎ

2022-08-01 10:58 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/group/controller/GroupController.java
> +    public ResponseEntity<GroupPageResponse> findAll(@PageableDefault(size=12) Pageable pageable) {
여기서 Pageable을 int형식으로만 받도록 변경하였으며, size 지정 등의 로직은 모두 서비스로 이동시켰습니다~

2022-08-01 14:37 UTC, Seongwon97 approved these changes

2022-08-02 00:19 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
> +                .collect(Collectors.toList());
GroupResponseAssembler에 GroupSummaryResponses 메서드를 만들고, 해당 로직을 옮겼습니다~😉

2022-08-02 00:40 UTC, merged