[BE] 로그 기능 추가
woowacourse-teams/2022-momo pull request #155
Opened 2022-08-01 06:50 UTC by kyukong

# ⚙️ 작업 내용
처리하지 않은 예외 발생 시 콘솔창 및 파일에 로깅 처리

# 🛠 상세 작업
- AOP 활용하여 로깅 기능 구현 (ExceptionLogging.java)
  - 로깅 관련 클래스는 `logging` 패키지에 위치
- 콘솔창에 로깅 처리
- 로그 파일에 로깅 처리
  - `src/log/{year}/{month}/{로그 파일}.txt` 에 위치

2022-08-01 08:08 UTC, Seongwon97 requested changes
AOP를 처음 사용하였어도 잘 사용하신 것 같아요!
피드백 몇개를 남겨봤는데 확인 부탁드려요!

2022-08-01 08:12 UTC, kyukong commented on backend/src/main/resources/application.yml
> +#    show-sql: 'true'
현재는 배포된 코드에서 로그를 남기지 않기 위해 주석처리 해두었을 뿐 이프 코드가 완성이 된다면 추후에 이프 코드를 선택하면 될 것 같습니다!

2022-08-01 08:19 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/logging/Logging.java
> +
`처리하지 못한 예외` 에 한해서 로그를 남겼습니다! 😊

2022-08-01 08:44 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/MomoApplication.java
>  public class MomoApplication {
반영했습니다! 좋은 리뷰 감사합니다 😊

2022-08-01 08:58 UTC, Seongwon97 approved these changes

2022-08-01 08:58 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/config/AspectConfiguration.java
> +}
설정 파일 변경 좋습니다👍

2022-08-01 12:11 UTC, sinb57 commented on backend/src/main/resources/application.yml
> +#    show-sql: 'true'
고려해주셔서 감사합니다~!!!

2022-08-01 12:21 UTC, sinb57 approved these changes
유콩~~ 고생많으셨습니다!! 코드가 너무 좋아요ㅎ 몇가지 리뷰 남겼으니 확인부탁드려요!!

2022-08-01 12:21 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/logging/ConsolePrettier.java
> +    private static final String ANSI_WHITE = "\u001B[37m";
사용하지 않는 색상에 대한 상수나 static 메서드는 추후에 사용할 계획이 있기 때문에 남기신 거겠죠?!

2022-08-01 12:21 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/logging/Logging.java
> +    @Pointcut("execution(* " + BASE_PATH + "." + EXCEPTION_PACKAGE + "." + GLOBAL_EXCEPTION_METHOD + "(..))")
문자열이 중복되기 때문에 상수분리를 하셨네요!! 중복제거를 위함이라는 점 동의하지만, 이런 경우 `코드 따라가기(command+click)` 같은 IDE의 도움을 받을 수 없게 되어요ㅜ 개인적으론 어노테이션에 사용되는 문자열에 대해 중복제거를 하지 않아도 괜찮다고 생각하는데, 고려해보시면 좋겠습니다~!!

2022-08-01 12:21 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/logging/LogFileManager.java
> +public class LogFileManager {
코드가 깔끔하네요!! 👍

2022-08-01 12:26 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/logging/ConsolePrettier.java
> +    private static final String ANSI_WHITE = "\u001B[37m";
현재는 사용 계획이 없으나(ㅠㅠ) 추후에 더 다양한 로그를 남긴다면 사용할 가능성이 있기 때문에 추가했습니다!

2022-08-02 01:26 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/logging/ConsolePrettier.java
> +    private static final String ANSI_WHITE = "\u001B[37m";
색상값은 매번 찾아보기 번거로워서 남겨두었고, 메서드는 사용하지 않는 것은 제거하였습니다

2022-08-02 01:57 UTC, merged