[BE] Google Oauth2 연동
woowacourse-teams/2022-momo pull request #213
Opened 2022-08-08 03:33 UTC by sinb57

# 🌟 구현 기능
Google Oauth2 연동에 대한 기능 구현

---

# 🛠 상세 작업
- [x] Google Oauth2 연동을 처리하는 Support 패키지 생성 및 하위 클래스 생성
- [x] Google Oauth2 접근에 대한 회원가입 및 로그인 처리 로직 구성
- [x] Google Oauth2 기능 로직에 대한 Controller 테스트 구현
- [x] Google Oauth2 정보를 담은 application.yml 생성 - Submodule(Security)로 관리
- [x] application.yml 관심사 분리 및 Profile 중복 제거 

close #212

2022-08-08 03:45 UTC, nbalance97 requested changes
일단 1차적으로 봤습니다~ 고생하셨습니다 이프ㅎㅎ

2022-08-08 03:45 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java
> +    private final GoogleProvider googleProvider;
Service가 구체적으로 Google인걸 알고 있는 것이 좋을까요?

2022-08-08 03:45 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java
> +                .orElseThrow(() -> new IllegalArgumentException("Google Oauth2 Request UserInfo - Non Exist Body"));
저 예외처리 따로 해뒀는데..ㅎ 속상하네요ㅎ

2022-08-08 03:52 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java
> +    private final GoogleProvider googleProvider;
필드명을 `oauthConnector`, `oauthProvider`로 변경했습니다~!!

2022-08-08 03:53 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java
> +                .orElseThrow(() -> new IllegalArgumentException("Google Oauth2 Request UserInfo - Non Exist Body"));
oauth에 대한 예외메시지를 어떻게 할지 구체적으로 의논이 필요해서! 임의로 처리해둔 상태입니다~

2022-08-08 10:42 UTC, kyukong approved these changes
리뷰 남긴 것들이 간단해서 바로 approve 할게요! oauth 구조가 처음 봤을 땐 어려웠지만 재미있었습니다~ 👍

2022-08-08 10:42 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java
> +        Member member = memberRepository.findByUserId(response.getEmail());
`MemberFindService` 에서 `Optional` 형식으로 받는 메서드를 만드는 것은 어떨까요? find 관련 메서드를 하나의 Service 로 관리 및 Optional 형식으로 통일을 할 수 있을 것 같아요.

2022-08-08 10:42 UTC, kyukong commented on backend/src/test/java/com/woowacourse/momo/auth/controller/OauthControllerTest.java
> +                        document("oauthLink",
카멜케이스로 할지 대소문자 구분없이 할지 통일하는 것이 좋을 것 같네요!

2022-08-09 01:49 UTC, Seongwon97 approved these changes
처음해보는 작업이셨을 텐데 코드를 깔끔하게 작성해주셨네요!
수고하셨습니다!!

2022-08-09 01:49 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java
> +    private final GoogleProvider oauthProvider;
추후 다른 클래스로 변경되었을 때 변동을 최소화하기 위함인거 같아요! 약간 List<Member>의 면수명을 memberList가 아니고 members로 하는 느낌? 인것 같네요

2022-08-09 01:49 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java
> +    }
다른 패키지들에서 예외 클래스들을 커스텀으로 분류한 만큼 OAuth 부분도 커스텀으로 묶어주면 좋을 것 같아요

2022-08-09 01:49 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/auth/support/google/GoogleConnector.java
> +                entity, GoogleTokenResponse.class);
RestTemplate을 사용하면 해당 라인을 통해 요청 및 반환을 한번에 받도록 되는걸까요.??
RestTemplate을 사용해본적이 없어 검색을 통해 찾아봤는데 확실하게 이해를 했나 몰라서 여쭤봅니다..ㅎ

2022-08-09 01:49 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/auth/support/google/GoogleConnector.java
> +    }
불필요한 메모리 절약을 위한 singleconList 👍

2022-08-09 01:49 UTC, Seongwon97 commented on backend/src/main/resources/application-logging.yml
> +#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
해당 설정은 개인 PC에서 개발을 하며 쿼리를 확인할때 사용하자고 커밋은 하지 말자고 했던 것 같아요!!

2022-08-09 01:49 UTC, Seongwon97 commented on backend/src/main/resources/application.yml
> -#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
어머 여기도 주석처리가 되어 있었네요😅 어떻게 관리 하기로 했었는지 혼란이 오네요

2022-08-09 02:30 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java
> +    private final GoogleProvider oauthProvider;
> Service가 구체적으로 Google인걸 알고 있는 것이 좋을까요?

맞습니다! 앞서 [라쿤이 언급이 언급한 내용](https://github.com/woowacourse-teams/2022-momo/pull/213#discussion_r939797614)도 이와 같은 내용입니다

2022-08-09 02:31 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/auth/controller/OauthController.java
> +        return ResponseEntity.ok(authUrl);
OauthLinkResponse DTO 객체에 매핑되도록 수정했습니다~~

2022-08-09 03:03 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/auth/support/google/GoogleConnector.java
> +            throw new IllegalArgumentException("Google Oauth2 Request AccessToken - Http Status 2xx Failed");
`MomoException`의 생성자가 `ErrorCode`으로 타입 제한되어 있고, 이를 위해선
`ErrorCode` Enum 클래스에 `상태코드,에러코드,메시지`를 작성해야하는데
해당 PR를 작성할 당시는 에러에 대한 회의가 진행되지 않았기에 표준 예외로 임시 처리해두었습니다~

어제 회의 안건에서 정해진 내용에 맞춰, 현재는 수정된 상황입니다! 확인부탁드려요

2022-08-09 03:03 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java
> +        Member member = memberRepository.findByUserId(response.getEmail());
Optional 형식으로 통일시켰습니다~

2022-08-09 03:06 UTC, sinb57 commented on backend/src/test/java/com/woowacourse/momo/auth/controller/OauthControllerTest.java
> +                        document("oauthLink",
아아! 해당 부분은 이번 PR이 머지된 이후에 별도의 이슈를 파서 진행할 사항입니다!!
지난번에 docs에 대한 명칭을 카멜케이스로 진행하자고 했어서, 곧바로 카멜케이스로 통일화할 예정입니다!
(~한줄요약: 나중에 할게요..ㅎㅎ~)

2022-08-09 03:07 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java
> +    }
`ErrorCode` Enum 클래스에 에러코드 명시했고, MomoException을 활용하여 예외처리를 수정했습니다!! 확인부탁드려요

2022-08-09 03:08 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/auth/support/google/GoogleConnector.java
> +                entity, GoogleTokenResponse.class);
넵! 요청이 이뤄지면서, 응답값이 지정된 클래스로 매핑되어집니다!!

2022-08-09 03:09 UTC, sinb57 commented on backend/src/main/resources/application-logging.yml
> +#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
개발 편의상 나뒀는데.. 지울까요?? 로그가 필요할 때마다 해당 설정 찾아보고 다시 적는 것보다는, 주석처리해뒀다가 필요할 때 주석을 해제하는 방식이 좋을 것 같다고 감히 판단했습니닷!! 의견 적극 반영할게요!! @nbalance97  @kyukong  어떠신가요?

2022-08-09 03:11 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/globalException/exception/ErrorCode.java
> +
추가된 에러코드입니닷

2022-08-09 03:12 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java
> +    }
추가된 에러코드는 다음과 같습니다

2022-08-09 03:12 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/auth/support/google/GoogleConnector.java
> +            throw new IllegalArgumentException("Google Oauth2 Request AccessToken - Http Status 2xx Failed");
추가된 에러코드는 다음과 같습니다 https://github.com/woowacourse-teams/2022-momo/pull/213#discussion_r940850371

2022-08-09 03:13 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java
> +                .orElseThrow(() -> new IllegalArgumentException("Google Oauth2 Request UserInfo - Non Exist Body"));
어제 회의된 내용에 따라 `ErrorCode` Enum 클래스에 에러코드 및 메시지를 지정하고 MomoExcpetion 커스텀 예외로 대체하였습니다!! 추가된 ErrorCode는 다음과 같슴다~ https://github.com/woowacourse-teams/2022-momo/pull/213#discussion_r940850371

2022-08-09 03:15 UTC, kyukong approved these changes
답변 남겨주신 것들 확인했습니다~ 적용하시느라 수고많으셨어요!!

2022-08-09 03:15 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/auth/support/google/GoogleConnector.java
> +    }
오옹.. 배우고 갑니다 👍

2022-08-09 03:15 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/auth/support/google/GoogleConnector.java
> +                .orElseThrow(() -> new MomoException(OAUTH_ACCESS_TOKEN_REQUEST_FAILED_BY_NON_EXIST_BODY));
변경된 것 확인했습니다~

2022-08-09 03:15 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/globalException/exception/ErrorCode.java
> +    OAUTH_USERINFO_REQUEST_FAILED_BY_NON_EXIST_BODY(HttpStatus.INTERNAL_SERVER_ERROR.value(), "OAUTH_ERROR_001", "구글에 요청한 회원정보에 대하여 응답 Body가 비어 있습니다."),
`OAUTH_ERROR_001` 로 통일한 것이 인상적이네요~ 좋습니다!!!

2022-08-09 03:15 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java
> +        return member.getId();
반환값이 Optional 로 바뀌었군요!! 😊 근데 아직 `MemberRepository` 에서 가져오고 있는데 `MemberFindService` 로 거치지 않는 이유가 있을까요?

2022-08-09 03:21 UTC, Seongwon97 approved these changes
고생 많으셨습니다!!

2022-08-09 03:21 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/member/service/dto/response/MemberResponse.java
> +@NoArgsConstructor
빈 생성자를 추가한 이유를 알 수 있을까요!?

2022-08-09 03:23 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/member/service/dto/response/MemberResponse.java
> +@NoArgsConstructor
이거 왠지 모르겠지만.. 지금 윈도우 데스크탑으로 작업중인데, 테스트가 깨지더라고요ㅠㅜ MemberResponse에 빈생성자가 없어서 리플렉션이 안된다구ㅠㅠ 그래서 추가했슴다

2022-08-09 03:49 UTC, nbalance97 approved these changes
이프 고생하셨습니다~

2022-08-09 03:49 UTC, nbalance97 commented on backend/src/main/resources/application-logging.yml
> +#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
주석으로 내버려 둬도 무방할것 같긴 해요ㅎㅎ

2022-08-09 03:50 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java
> +        return member.getId();
와우,.. 날카롭네요!! 역시 유콩~!!ㅋㅎㅎ

`OauthService#findOrSaveMember`에서 사용하고 있는 `memberRepository#findByUserId`의 로직을 보시면, 반환값이 없는 경우 에러를 발생시키는 것이 아니라 새롭게 저장하고 그 반환값을 리턴하도록 되어있어요!!

즉, 현재 선언되어 있는 `MemberFindService#findMember`를 사용할 수 없는 상황이에요.
`OauthService#findOrSaveMember`에서 `try-catch`로 로직을 처리할 것이 아니라면,
`MemberFindService`에 `Optional<Member>`를 반환하는 `findMember`를 만들어서 조회를 해와야 겠죠.
그렇다면 아래의 코드가 `MemberFindService`에 추가될텐데, 해당 코드는 `memberRepository#findById`를 그대로 사용하는 것과 다를 바가 없어요.
```java
    public Optional<Member> findMember(Long id) {
        return memberRepository.findById(id);
    }
```

`MemberFindService`에 위의 로직을 넣음으로써 얻게 되는 장점이 무엇일까요.
관심사에 따라 의존성을 분리할 수 있겠죠!! Member에 대한 조회 기능만 필요로 한 상황에서, `MemberRepository`의 의존성을 끌고 오면서까지 `CUD 기능` 접근을 열지 않아도 되니까요!!
그리고 Member 조회에 대한 전반적인 책임을 수행하는 `MemberFindService`의 역할을 뚜렷히 할 수 있죠!! 유지보수가 편해질 수 있겠네요!

하지만 현재 `OauthService`가 맺고 있는 의존성을 살펴보면 달리 생각해야해요. `OauthService`는 `MemberRepository`를 알고 있어요. `MemberRepository`를 통해 필요한 작업을 모두 진행할 수 있죠. 더군다나 해당 작업에 사용되는 로직은 `MemberFindService`에 있는 것과 같이 다른 클래스에도 분포되어 있는 `예외처리로직` 중복로직이 아니라, 지금 현재 여기에만 존재하고 있어요. 따라서 중복을 제거한다는 개념은 아직 드러나지 않은 상황이에요. 그렇다면 생각할 수 있는 부분은 의존성의 측면인데, `MemberRepository`만으로도 충분한 상황에서 `MemberFindService`를 엮어야 할까요? 더군다나 `MemberFindService`가 행하는 일이 `MemberPository`의 메서드를 그저 호출하는 것일 뿐인데 말이죠. 저는 해당 부분 때문에 굳이 하나의 의존성을 더 엮을 필요가 없다고 생각했어요. Member 조회의 책임을 수행하고 있다는 이유로 `MemberFindSerivce`에 `Optional<Member>를 리턴하는 findMember`를 만들어두어도, 사용되는 곳이 없기 때문에 더더욱 이유를 찾지 못했죠.

2022-08-09 03:57 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/member/service/dto/response/MemberResponse.java
> +@NoArgsConstructor
역시 윈도우가 문제네요..

2022-08-09 03:58 UTC, kyukong commented on backend/src/main/resources/application-logging.yml
> +#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
주석으로 두고 필요할때만 사용하는것도 좋을 것 같습니다~!

2022-08-09 04:04 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java
> +        return member.getId();
그럼 findService 에 대한 규칙(?)을 새로 정하는 것이 좋을 것 같습니다! 저는 단순하게 find~ 의 이름을 가지고 있으니 Repository 에서 호출하는 **모든** 조회 메서드를 관리해야 한다고 생각헀어요. 다만 지금처럼 조회하면서 다른 로직이 필요한 경우가 앞으로도 있을 수도 있죠! 

따라서 조회할 때 조회하는 것 외의 다른 로직이 없을 경우에만 findService 에서 가져오면 될 것 같네요. 조회하면서 다른 로직이 포함되어 있는 코드가 중복적으로 발생한다면 그 때 어떻게 리팩토링할 지 의논해보는건 어떤가요? 😊

2022-08-09 04:08 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java
> +        return member.getId();
좋습니다~!!

2022-08-09 04:12 UTC, merged