[BE] 회원 탈퇴 기능 구현
woowacourse-teams/2022-momo pull request #269
Opened 2022-08-15 08:19 UTC by kyukong

## 🌟 구현할 기능
회원 탈퇴 기능을 구현한다.

## ⚒️ 작업 내용
- 회원 탈퇴 기능 구현
  - 회원 탈퇴 시 탈퇴 여부 컬럼에 표시
  - 참여중인 모임이 모집중인 경우 참여자 목록에서 삭제
  - 참여중인 모임이 모집 마감 되었을 경우 유령 계정 정보로 변경
  - 주최한 모임이 모집 마감되었을 경우 유령 계정 정보로 변경
- 주최한 모임이 모집중일 경우 탈퇴 불가능

2022-08-15 08:34 UTC, sinb57 approved these changes
고생 많으셨습니다 유콩~

2022-08-15 08:34 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/member/service/MemberFindService.java
> +    }
삭제된 회원인지에 대한 검증 로직이 왜 필요한지 궁금합니다!

2022-08-15 08:34 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/member/service/MemberService.java
> +        withdrawGroup(member);
좋은 단어가 떠올랐어요!! `withdraw` 대신 `leave` 어떠신가요??

2022-08-15 08:34 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/member/domain/Member.java
> +        this.deleted = true;
왜 `deleted`에만 `this.`가 붙어있나요???

2022-08-15 08:35 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/member/domain/Member.java
> +        this.deleted = true;
허거덩 지웠어요~!ㅜㅜ

2022-08-15 08:43 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/member/service/MemberFindService.java
> +    }
로그인 하거나 회원 정보를 조회할 때 등 삭제된 회원에 대해서 기능을 제한하려고 검증했습니다. 해당 피드백을 보고 빠트린 부분도 추가했습니다!ㅎㅎ

2022-08-15 11:48 UTC, nbalance97 requested changes
유콩 안녕하세요~ 빨간날인데도 고생 많으셨습니다!

간단한 리뷰 남겼으니 의견 부탁드려요🙂

2022-08-15 11:48 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/member/service/MemberService.java
> +            participantRepository.deleteByGroupIdAndMemberId(group.getId(), member.getId());
반복문 내부를 조금 더 깔끔하게 할 수 있을것 같아요!
본인이 호스트인 그룹이 있는지 확인하는 메서드를 하나 따로 두는 것은 어떨까요?

2022-08-15 11:57 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/member/service/MemberService.java
> +            participantRepository.deleteByGroupIdAndMemberId(group.getId(), member.getId());
```java
            if (group.isHost(member)) {
                throw new MomoException(ErrorCode.MEMBER_DELETED_EXIST_IN_PROGRESS_GROUP);
            }
```
이 부분을 메서드로 분리하자는 말씀이실까요?? 😅 따로 분리할 수는 있지만 많이 길지 않은 로직이며 하나의 반복문 내에서 전부 보여주는 것도 괜찮다고 생각해 분리하지는 않았습니다!!

사실 처음엔 이렇게 하고 싶었는데 중복적인 지점이 있어 사용하지 않았습니다.
```java
            if (group.isHost(member) && !group.isEnd()) {
                throw new MomoException(ErrorCode.MEMBER_DELETED_EXIST_IN_PROGRESS_GROUP);
            }
            if (!group.isEnd()) {
                participantRepository.deleteByGroupIdAndMemberId(group.getId(), member.getId());
            }
```
첫번째 방식(처음에 제출한 방식)으로 하면 중복적인 부분은 제거할 수 있으나 어떤 로직이 있는지 파악하기 어렵습니다. 두번째 방식(바로 위에 작성한 방식)으로 하면 중복적인 코드는 있으나 명시적으로 어떤 것들을 검증하려는지 알 수 있습니다. 라쿤은 어떤 방식을 더 선호하시나요?

2022-08-15 12:46 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/member/service/MemberService.java
>      }
```suggestion
    @Transactional
    public void deleteById(Long id) {
        Member member = memberFindService.findExistMember(id);
        
        leaveProgressingGroups(member);
        
        member.delete();
    }

    private void leaveProgressingGroups(Member member) {
        List<Group> progressingGroups = groupFindService.findRelatedGroups(member.getId())
                .stream()
                .filter(group -> !group.isEnd())
                .collect(Collectors.toList());

        validateMemberNotHost(member, progressingGroups);

        progressingGroups.forEach(
                group -> participantRepository.deleteByGroupIdAndMemberId(group.getId(), member.getId()));
    }

    private void validateMemberNotHost(Member member, List<Group> groups) {
        if (isMemberHost(member, groups)) {
            throw new MomoException(ErrorCode.MEMBER_DELETED_EXIST_IN_PROGRESS_GROUP);
        }
    }

    private boolean isMemberHost(Member member, List<Group> groups) {
        return groups.stream()
                .anyMatch(group -> group.isHost(member));
    }
```

저라면 이렇게 리팩터링했을 듯 합니다

2022-08-16 00:30 UTC, Seongwon97 approved these changes
휴일중에도 개발하느라 수고 많으셨습니다👍👍

2022-08-16 00:30 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/member/domain/Member.java
> +    }
getter에서 이미 똑같은 `isDeleted()`
를 제공하고 있을텐데 추가적으로 메서드를 작성한 이유가 있을까요?

2022-08-16 00:30 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/member/service/MemberService.java
> +        List<Group> groups = groupFindService.findRelatedGroups(member.getId());
헉...기능구현하면서 해당 메서드 제거했는데...벌써부터 rebase가 걱정이네요🥲

2022-08-16 00:30 UTC, Seongwon97 commented on backend/src/test/java/com/woowacourse/momo/member/service/MemberServiceTest.java
> +    }
Group클래스에 있는 `participate()`메서드를 사용할 수 있지 않을까요

2022-08-16 00:30 UTC, Seongwon97 commented on backend/src/test/resources/init.sql
> +    deleted  boolean default false,
머지되면 배포 DB서버에도 컬럼 추가해야겠네용👍

2022-08-16 00:30 UTC, Seongwon97 commented on backend/src/test/java/com/woowacourse/momo/acceptance/member/MemberAcceptanceTest.java
> +            .getGroupId();
바로 위의 `~로 로그인한다`메서드처럼 static 메서드에서 바로 groupId를 반환해도 좋을 것 같습니다

2022-08-16 01:55 UTC, kyukong commented on backend/src/test/java/com/woowacourse/momo/acceptance/member/MemberAcceptanceTest.java
> +            .getGroupId();
와 세상에 미리 만들어져 있었군요!!!! 바로 사용했습니다!

2022-08-16 02:07 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/member/service/MemberFindService.java
> +    }
삭제된 회원이 해당 기능을 사용하는 경우가 없다고 판단되어요!! 검증 로직이 필요없다고 생각되네요~!

2022-08-16 02:12 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/member/service/MemberService.java
> +            participantRepository.deleteByGroupIdAndMemberId(group.getId(), member.getId());
아 너무 좋네요 바로 반영했습니다!ㅎㅎ

2022-08-16 02:21 UTC, nbalance97 approved these changes
Approve 해드렸습니다~~

2022-08-16 02:30 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/member/service/MemberFindService.java
>      }
검증 로직이 왜 필요한지 아직 잘 모르겠어요~~~

2022-08-16 02:36 UTC, sinb57 approved these changes
좋아유~

2022-08-16 02:37 UTC, merged