[BE] 비밀번호 확인 API 구현
woowacourse-teams/2022-momo pull request #285
Opened 2022-08-16 10:08 UTC by Seongwon97

# Issue
- #283 

#  🌟 구현할 기능
비밀번호 확인 API 구현

# 🛠 상세 작업 
비밀번호를 입력받아 회원의 비밀번호와 맞는지 확인하는 API 구현

## Request
```
PUT /api/members/password/confirm HTTP/1.1
Content-Type: application/json;charset=UTF-8
authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMTYiLCJpYXQiOjE2NjA2NDQzMzMsImV4cCI6MTY2MDY0NjEzM30.GEn29aS6qF6kvUEot5JkepxdljoclnLWXlwENYFloIQ
Content-Length: 30
Host: localhost:8080

{
  "password" : "1q2W3e4r!"
}
```

## Response
```
HTTP/1.1 200 OK
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
```

# ⏰ 예상 소요 시간
20분

2022-08-16 11:56 UTC, nbalance97 approved these changes
렉스 빠르게 구현해 주셨네요~~🫡

간단한 리뷰 남겼으니 확인해 주세요! 로직 자체는 괜찮아 보여 Approve 하겠습니다!

2022-08-16 11:56 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/member/domain/Member.java
> +
이거 `confirmWrongPassword`로 꼭 해야할까요? 생각보다 의미 전달이 잘 안되는거 같아요ㅎㅎ

2022-08-16 14:56 UTC, kyukong approved these changes
렉스! 아주 빠른 구현 좋습니다!! 빠르지만 꼼꼼하게 작성해주신 것 같아서 바로 approve 할게요! 🦖

2022-08-16 14:56 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/member/controller/MemberController.java
> +    @PutMapping("/password/confirm")
비밀번호 확인에서 사용하는 method 를 put 으로 하셨군요! 정해진 방식을 벗어나는 API 에 대한 method 정하기가 어렵던데, 혹시 왜 put 을 선택했는지 알 수 있을까요? 궁금합니다!! 🤔

2022-08-16 14:56 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/member/service/dto/request/PasswordRequest.java
>      private static final String PASSWORD_PATTERN = "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[~!@#$%^&*()+|=])[A-Za-z\\d~!@#$%^&*()+|=]{8,16}$";
com/woowacourse/momo/auth/service/dto/request/`SignUpRequest`.java 에 있는 로직과 동일한 것 같은데 이후에 리팩토링할 때 정규식 검증하는 static 클래스를 만드는 것은 어떨까요? 생각난김에 미리 적어둡니다ㅎㅎ

2022-08-16 14:56 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/member/domain/Member.java
> +
동의합니다~ `Member` 입장에서는 받아온 `password` 와 실제 `password` 가 동일하지 않은지 확인하는 것이므로 `isNotSame()` 은 어떨까요?

2022-08-16 14:56 UTC, kyukong commented on backend/src/test/java/com/woowacourse/momo/member/service/MemberServiceTest.java
> +    @DisplayName("잘못된 비밀번호면 예외가 발생한다")
이 설명만으로는 테스트 돌릴 때 어떤 테스트에서 실패하는지 바로 파악하기 어려울 것 같아요. 어떤 행위를 하는지 앞에 추가하는 것은 어떨까요?

```suggestion
    @DisplayName("비밀번호 확인 시 입력한 값이 잘못된 비밀번호면 예외가 발생한다")
```

2022-08-16 23:11 UTC, sinb57 requested changes
렉스 고생하셨어요!! 궁금한 내용이 있어서 코멘트 남겨두었습니다

2022-08-16 23:11 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/member/controller/MemberController.java
> +    public ResponseEntity<Void> confirmPassword(@AuthenticationPrincipal Long id,
해당 api의 존재 이유를 잘 모르겠어요!! 정확히는 `updateName이랑 왜 분리되어있는가?`가 궁금합니다

2022-08-16 23:11 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/member/controller/MemberController.java
> +                                                @RequestBody PasswordRequest request) {
다른 메서드와는 달리 여기는 `@Valid`가 없네요?? `@Valid`가 무슨 역할을 하는지 궁금합니다!!

2022-08-17 00:11 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/member/domain/Member.java
> +
유콩의 의견대로 isNotSamePassword()로 수정을 해보겠습니다!

2022-08-17 00:12 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/member/service/dto/request/PasswordRequest.java
>      private static final String PASSWORD_PATTERN = "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[~!@#$%^&*()+|=])[A-Za-z\\d~!@#$%^&*()+|=]{8,16}$";
좋습니다~패스워드의 중복 코드 제거 좋습니다

2022-08-17 00:12 UTC, Seongwon97 commented on backend/src/test/java/com/woowacourse/momo/member/service/MemberServiceTest.java
> +    @DisplayName("잘못된 비밀번호면 예외가 발생한다")
좋습니다! 바로 반영해보겠습니다

2022-08-17 00:14 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/member/controller/MemberController.java
> +    public ResponseEntity<Void> confirmPassword(@AuthenticationPrincipal Long id,
해당 내용은 이전 회의를 통해 정해진 내용이 아닐까요..??
updateName은 말 그대로 이름을 업데이트하는 api고 해당 api는 수정 페이지로 들어가기 전에 비밀번호를 확인하는 api로 역할 자체가 다른 것 같습니다

2022-08-17 00:17 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/member/controller/MemberController.java
> +                                                @RequestBody PasswordRequest request) {
저는 NotBlank와 email password패턴 검증 등은 1차적으로 dto에서 걸러주는 스타일인데..다른 곳에서 valid 사용을 안하여서 일단 보류했습니다

2022-08-17 00:18 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/member/controller/MemberController.java
> +                                                @RequestBody PasswordRequest request) {
valid 사용에 동의하신다면 오후에 프러젝트에 전반적으로 NotBlank와 같이 빈 값에 대한 잘못된 입력 검증 추가들을 해보겠습니다

2022-08-17 00:20 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/member/controller/MemberController.java
> +    @PutMapping("/password/confirm")
프로젝트 초기에 회의를 하면서 해당 API는 PUT으로 만들자고 했던거로 기억합니다! 노션에도 비밀번호 확인 API가 PUT으로 되어 있더군요..!

2022-08-17 02:30 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/member/controller/MemberController.java
> +    public ResponseEntity<Void> confirmPassword(@AuthenticationPrincipal Long id,
회의 내용을 반영하여 합치도록 하였습니다!!👍

2022-08-17 03:42 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/member/controller/MemberController.java
> +    @PutMapping("/password/confirm")
회의에서 비밀번호 수정 API와 통일되어 Patch로 통한 변경이 됐습니당

2022-08-17 03:55 UTC, sinb57 approved these changes

2022-08-17 03:56 UTC, merged