[BE] 도메인 값 객체 분리
woowacourse-teams/2022-momo pull request #316
Opened 2022-08-21 13:16 UTC by kyukong

## ✨ Issue
- #290 

## 🌟 구현할 기능
도메인 객체 내에서의 값 객체들을 분리한다. (+ 리팩토링..)

## 🛠 상세 작업
- 도메인 내 값 객체 분리 + 테스트 추가
- DTO 에서 검증하던 로직들을 도메인으로 이동
- 서비스 계층에서 하던 로직들을 도메인으로 이동
- validate 메서드 형식 변경 (예. validate (that) S + V)
- 에러 코드 static 으로 import
- 검증 로직이 많은 Group 은 검증 절차에 템플릿 콜백 패턴 적용 (`ExceptionPredicate`)
- 사용자 아이디 및 비밀번호 패턴 검증 객체 별도 생성 (`MemberPattern`)
- 처리하지 못한 예외 발생 시 해당 메서드를 찾는 방식을 어노테이션으로 변경 (`UnhandledErrorLogging`)
- .gitignore 에 로그 관련 추가

2022-08-22 04:40 UTC, sinb57 requested changes
유콩~!! 방학인데 고생많았어요! 엄청난 양의 리팩토링이군요
얼마나 고생하셨을지 엿보이는 작업물이에요.
양이 많은지라, 리뷰도 많은데 하나씩 확인 부탁드려요

+남기시는 답변보고서 `Resolve conversation`은 제가 확인하고 닫겠습니다.

2022-08-22 04:40 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/calendar/Schedule.java
> +    }
메서드 배치 순서에 대한 컨벤션은 다 같이 얘기나누는 것이 좋아보여요
@kyukong @Seongwon97 @nbalance97

2022-08-22 04:40 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> +        participants.participate(this, member);
참여인원이 capacity를 초과했는지에 대한 검증 로직이 필요해보여요

2022-08-22 04:40 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
>      }
`validateGroupIsInitialState`에서만 쓰이고 있어요! `private`로 바꾸는 것은 어떨까요

2022-08-22 04:40 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
> +        Member host = memberFindService.findMember(hostId);
`hostId`와 `groupId` 간의 관계를 `Group#update`를 지나 `Group#validateGroupIsInitialState`에서 확인하고 있어요. 모임과 회원 간의 일치여부를 확인하기 이전에 많은 로직을 지나치고 있는데, 이러 검증에 대해서는 `GroupService#update`에서 바로 처리하는 것이 좋아보여요. early return!!

2022-08-22 04:40 UTC, sinb57 commented on backend/src/test/java/com/woowacourse/momo/group/domain/calendar/CalendarTest.java
> +}
크아아 개행

2022-08-22 04:40 UTC, sinb57 commented on backend/src/test/java/com/woowacourse/momo/member/domain/UserNameTest.java
> +        assertThatThrownBy(() -> new UserName("a".repeat(31)))
`repeat` 👍👍👍

2022-08-22 04:40 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/participant/domain/Participants.java
> +    }
```suggestion
    public Participants(Group group) {
        value.add(new Participant(group));
    }
```
`member`가 필요한지 의문이에요!!

저번에 말씀주셨을 때의 문제가 아래 `Participant` 생성자 때문이죠?!
```java
    public Participant(Group group, Member member) {
        this.group = group;
        this.member = member;
    }
```
그렇다면 달리 생각해봐서, `Participant` 생성자에 member가 필요할까요?
```java
    public Participant(Group group) {
        this.group = group;
        this.member = group.getHost();
    }
```

2022-08-22 04:40 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
>      }
그리고 해당 검증로직이 `모임 수정`에만 적용되어 있네요ㅠ `모임 생성`에도 적용되도록 해야겠어요

2022-08-22 04:40 UTC, sinb57 commented on backend/src/test/java/com/woowacourse/momo/member/domain/UserIdTest.java
> +}
🙄EOF

2022-08-22 04:40 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
>      }
ㄴ (File Changed가 아니어서 여기 적어놉니다.)
`모임 생성`에 검증로직을 추가하니 `GroupFindServiceTest`와 `GroupServiceTest`가 실패하네요.
각 테스트 클래스의 `constructGroup`메서드에서 필드값이 잘못 지정되어 있어요.
`이틀후_10시부터_12시까지`가 `일주일후_10시부터_12시까지`이어야겠네요.

2022-08-22 04:40 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/ExceptionPredicate.java
> +}
😄

2022-08-22 04:40 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
>      }
`validate`라는 메서드명도 좋아보여요!

2022-08-22 04:40 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
>      }
람다식을 적극활용해서 ExceptionPredicate에 의미부여를 해도 좋아보여요 (`this::의미`)

2022-08-22 04:40 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> +        validateTemplate((() -> isHost(member)), PARTICIPANT_LEAVE_HOST);
불필요한 괄호 사용을 줄일까요? ide도 권장하네요

2022-08-22 05:08 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/participant/domain/Participants.java
> +    private static final int NONE_PARTICIPANT = 1;
헉~! 지웠어요!! 😅

2022-08-22 05:09 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/member/domain/UserId.java
> +    private static final String EMAIL_PATTERN = "@";
왜 다 남아있을까요..ㅋㅋㅋㅋ 감사해요~!

2022-08-22 06:04 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/calendar/Calendar.java
> +    public Calendar(List<Schedule> schedules, Duration duration, LocalDateTime deadline) {
수정하면서 그 외의 객체들도 객체로 받아오도록 수정하였습니다~
- GroupName
- Capacity
- Deadline

2022-08-22 06:59 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/member/domain/MemberPattern.java
> +    private static final Pattern PASSWORD_PATTERN = Pattern.compile(PASSWORD_FORMAT);
아쉽네요..🥲

2022-08-22 07:23 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
>      }
`participants.isExist()` 만으로도 충분한 의미 전달이 이루어질 것같아 메서드를 제거하고 participants.isExist() 를 그대로 사용하였습니다

2022-08-22 07:28 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> +        validateTemplate((() -> isHost(member)), PARTICIPANT_LEAVE_HOST);
혹시 어떤 방식을 말씀하시는지 예시로 작성해주실 수 있을까요? 저는 IDE 가 알려주지 않네요...ㅠㅠ

2022-08-22 07:30 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
>      }
어떤 걸 말씀하시는지 제대로 이해하지 못했습니다...!! 😂

2022-08-22 07:40 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
> +        Member host = memberFindService.findMember(hostId);
`Group#validateGroupIsInitialState` 에 있는 `validate((() -> !isHost(member)), AUTH_DELETE_NO_HOST);` 코드 부분을 말씀하시는 걸까요? 도메인에서 하던 검증을 서비스로 다시 옮긴다면 빠른 검증을 할 수 있다는 장점이 있겠으나, 

1. 서비스 계층에서 하는 검증과 도메인에서 하는 검증의 기준이 명확하지 않음
2. 그룹 수정에 관한 검증 로직의 위치가 분리됨
3. 그룹 수정 메서드를 다른 곳에서 호출할 경우 기존 서비스 계층에서 하던 검증 로직을 빠트릴 수 있음

등의 문제가 있을 것 같습니다.. 아니면 서비스 계층과 도메인에서 하는 검증 로직에 대한 기준이 따로 있으실까요? 🧐

2022-08-22 07:41 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> +        participants.participate(this, member);
아앗... 발견되기 전에 수정하려고 했는데 이미 리뷰를 주셨었군요..ㅎㅎ...

2022-08-22 07:49 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> +        validateTemplate((() -> isHost(member)), PARTICIPANT_LEAVE_HOST);
```suggestion
        validateTemplate(() -> isHost(member), PARTICIPANT_LEAVE_HOST);
```
이렇습니다~!

2022-08-22 07:51 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
>      }
람다식이라고만 해서 이해가 안되셨겠네요ㅎㅎ;; 람다식 축약을 의미했습니다!

```java
        validateTemplate((() -> !isHost(member)), AUTH_DELETE_NO_HOST);
        validateTemplate((this::isFinishedRecruitment), GROUP_ALREADY_FINISH);
```
두 행을 보시면 첫번째 행보다 두번째 행이 의미를 더 드러내고 있어요.
이와 같이 메서드 추출을 통해 의미부여를 하는 것이 좋아보인다는 의견입니다~

2022-08-22 08:03 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
> +        Member host = memberFindService.findMember(hostId);
현재 `Group` 클래스에 존재하는 검증로직 `validateMemberCanLeave` `validateGroupIsInitialState` `validateGroupCanBeCloseEarly`을 보면 공통점이 있습니다.

공통적으로 위의 검증 로직들은 2단계로 구분되는데요.  매개변수로 주어진 member가 해당 모임의 주최자인지 확인하는 검증(이하 1단계라고 명칭), 그리고 2차적으로 모임이 어떠한 행위(수정 등)를 할 준비가 되었는지에 대한 검증(이하 2단계라고 명칭). 이렇게 두 단계로 분리됩니다.

이 때, 2단계는 도메인 계층에서 처리되는 것이 맞다고 생각되나
1단계는 서비스 계층에서 처리되어도 된다고 판단하고 있습니다.

2022-08-22 08:08 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/auth/service/AuthService.java
> +        Optional<Member> member = memberRepository.findByUserId(new UserId(userId));
일단 알려주신 메서드의 매개변수는 객체를 받도록 수정했습니다! 😄

> 이와 더불어 Request DTO의 getter로직이 값객체를 생성해서 반환하는 방식은 어떻게 생각하는지 궁금해요.

DTO 는 외부(controller) 와 밀접하게 접근하는 계층이다보니 약간의 거부감이 생기기는 하네요.. Request DTO 라고 집어주신거는 Request DTO 에서만 사용하고 Response DTO 에서는 사용하지 않을 계획이라서 그런거겠지요?

객체로 변환하는 곳은 개발 초기 단계에서 만들어둔 GroupRequestAssembler 등의 어셈블러를 이용하면 되지 않을까요? 해당 객체의 메서드들이 이미 getter 의 역할을 하고 있는 듯 보여요.

2022-08-22 08:18 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/calendar/Duration.java
> +    }
생성자를 생성하는 과정에서 예외가 발생한다면(적절하지 않은 값이 들어오면) 해당 객체는 생성되지 않기 때문에 안전하지 않은 방식이라고는 생각하지는 않았습니다.

객체를 생성할 때 입력한 값들을 검증하는 과정이기 때문에 검증이 완료된 값들은 다시 객체의 값으로 할당됩니다. 이 과정이 중복적이라고 느껴져 미리 값을 할당시킨 후 해당 값을 호출하여 검증하였습니다. 이프가 말씀해주신 것처럼, 값을 지정한 후 검증하기 때문에 값을 지정하는 과정이 어떻냐에 따라 시간이 걸릴 수 있으나 현재까지는 그렇게 오래 걸리는 과정이 없다고 생각합니다.

또한 값을 지정 후 검증한다면 코드도 간결해지고 검증 메서드 내부에서 필요로 하는 값이 변경될 경우 메서드를 사용하는 곳에서의 변경점이 적다고 생각했습니다.

이 부분은 다른 팀원들과 더 상의해볼까요?

2022-08-22 09:00 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/calendar/Duration.java
> +    }
속도의 문제가 아닌 메모리 관점에서는 `할당 후 검증` 보다 `검증 후 할당`이 옳아보입니다.
Duration 클래스는 적절치 않으니 `Group#update` 로직을 예로 들겠습니다.

```java
    public void update(String name, Member host, Category category,
                       int capacity, Duration duration, LocalDateTime deadline,
                       List<Schedule> schedules, String location, String description) {
        this.name = new GroupName(name); // GroupName 생성
        this.category = category;
        this.capacity = new Capacity(capacity); // Capacity 생성
        this.location = location;
        this.description = description;
        calendar.update(schedules, duration, deadline); // Calender#update 내부에선 Deadline 생성
        validateGroupIsInitialState(host);
    }
```

위의 로직 하단에 존재하는 검증 로직이 통과되지 않으면 Group 객체는 update되지 않습니다.
하지만 검증이 이뤄지기 전에 수행된 행들에 의해 여러 객체들이 생성됩니다.
이러한 객체 생성은 Service에서 적용된 `@Transactional`(-> DB에 대한 제약)과는 달리
객체가 사라지지 않고 계속해서 메모리에 남게 되고 GC에 의해 지워지기를 기다립니다.
이러한 행위들이 야기하는 것으 불필요한 메모리 공간 차지이고 잦은 GC 실행입니다.

예로부터 `검증 후 할당`과 `할당 후 검증`은 많은 의견이 주고받아졌다고 알고 있지만,
개인적으론 위와 같이 불필요한 객체 생성으로 인한 메모리 차지 때문만이라도 `검증 후 할당`이 옳다고 생각합니다.

현재로서는 내부적으로 객체를 생성하지 않는 생성자가 존재하거나 많아봤자 1,2개의 객체를 생성하기 때문에
메모리 관점을 생각할 필요가 없다고 하기에는 `할당 후 검증`이 하나의 컨벤션으로서 정립된 이후엔
해당 컨벤션으로 작성될 추후의 로직들을 고려했을 때, 불필요한 메모리 공간차지에 의한 이슈발생은
처음부터 방지하는 것이 옳다고 생각합니다.

+과도한 로직 작성이 아니라 지극히 컨벤션에 대한 내용이므로
+해당 관점은 오버 엔지니어링이 아니라고 판단합니다.

2022-08-22 09:14 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/auth/service/AuthService.java
> +        Optional<Member> member = memberRepository.findByUserId(new UserId(userId));
제가 생각하는 바를 온전히 적지 않았네요ㅎㅎ;;

아마 `validateUserNotExist`가 매개변수로 UserId 타입을 받도록 하는 과정에서 아래와 같이 로직을 변경했으리라 생각해요.
```java
    @Transactional
    public Long signUp(SignUpRequest request) {
        validateUserNotExist(new UserId(request.getUserId()));
        Password password = Password.encrypt(request.getPassword(), passwordEncoder);
        Member member = new Member(request.getUserId(), password, request.getName());
        Member savedMember = memberRepository.save(member);

        return savedMember.getId();
    }
```

로직을 살펴보면, validateUserNotExist 메서드에 매개변수로 넘기기 위해 UserId 값객체를 생성하는데요.
그러곤 Member 생성자에 UserId 원시값을 집어넣고 생성자 내부에서 다시 UserId 값객체를 생성하고 있어요.
중복되는 행위인 것이죠. 그래서 저는 이러한 변경을 생각했어요.

```java
    @Transactional
    public Long signUp(SignUpRequest request) {
        UserId userId = new UserId(request.getUserId());
        UserName userName = new UserName(request.getName());
        Password password = Password.encrypt(request.getPassword(), passwordEncoder);

        validateUserNotExist(userId);
        Member member = new Member(userId, password, userName);
        Member savedMember = memberRepository.save(member);

        return savedMember.getId();
    }
```
이러면 UserId 값객체 생성에 대한 중복을 제거할 수 있죠. 그리고 Member 생성자의 매개변수 타입을 통일하기 위해 userName 또한 값객체로 생성해서 넘길 수 있어요. 그런데 이러니까 `signUp`로직이 길어지잖아요.

그래서 다시금 리팩터링한다면 최종적으로 아래와 같이 변경할 것 같아요.
```java
    @Transactional
    public Long signUp(SignUpRequest request) {
        validateUserNotExist(request.getUserId());
        Member member = MemberRequestAssembler.member(request);
        Member savedMember = memberRepository.save(member);

        return savedMember.getId();
    }
```

2022-08-22 09:54 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/member/domain/UserId.java
> +    }
DB 에 저장된 값을 읽어와 영속 컨텍스트에 객체를 저장할 때 빈 생성자가 필요합니다.. 엔티티가 아닌 일반 객체도 모두 필요하더라구요ㅠㅠ🥲

2022-08-22 13:47 UTC, Seongwon97 approved these changes
유콩 방학중에도 이렇게나 열심히 해주시다니 너무 수고 많으셨어요!!
파일 체인지가 많았지만 전반적으로 값객체 분리와 dto에 valid추가 static ErrorCode의 Prefix제거라 잘 읽혔던 것 같아요!!!
코드를 보며 피드백을 조금 남겨봤어요!!
확인 부탁드립니당👍

2022-08-22 13:47 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/calendar/Duration.java
> +    }
아주 좋은 토론이군요!! 저는 이프의 말대로 `검증 후 할당`!을 하는 것이 좋다고 생각됩니다. 
생성 이후에도 계속 사용되는 검증 로직이면 외부에서 주입이 아닌 객체 내부의 필드값을 사용하면 되어서 `검증 후 할당`이 좋겠으나 현재 우리의 대부분의 검증 로직들은 생성시에만 검증되는 것이기에 검증 로직을 필요한 값을 인자로 넘겨서 검증하도록 바꾸며 `검증 후 할당`으로 변경하면 좋을 것 같습니다!!

2022-08-22 13:47 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/ExceptionPredicate.java
> +}
오~고급 기술을 사용하셨네요👍

2022-08-22 13:47 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> -        }
확실히 값 객체로 분리하니까 Group 도메인의 크기가 줄어들었네요👍

2022-08-22 13:47 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/GroupSpecification.java
> +            return criteriaBuilder.greaterThan(root.get("calendar").get("deadline"), criteriaBuilder.currentTimestamp());
유콩도 이제 JPA Specification 마스터..??

2022-08-22 13:47 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/participant/domain/Participants.java
> +}
리펙터링한 코드들의 컨벤션이면 해당 메서드는 public이라 위로 올라가는게 좋을것 같습니다!

2022-08-22 13:47 UTC, Seongwon97 commented on backend/src/test/java/com/woowacourse/momo/participant/controller/ParticipantControllerTest.java
> +        fieldDeadline[index].set(deadline, date);
이제 리플렉션을 반대하던 유콩은 역사속에만 존재하는군요🤣

2022-08-22 14:05 UTC, sinb57 requested changes
유콩~ 늦은시간 고생많았어요!! 앞선 리뷰에 대한 변경점과 코멘트 확인했습니다!
새로운 리뷰와 더불어 기존에 남겼던 리뷰에 대한 코멘트에도 답변 남겼습니다!!

2022-08-22 18:28 UTC, nbalance97 requested changes
유콩~ 방학인데도 불구하고 리팩토링 진행하시느라 고생 많으셨어요 😂

코멘트 몇개 남겼으니 확인 부탁드려요~

2022-08-22 18:28 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/GroupCapacityRange.java
> +        return (MINIMUM.number > capacity) || (capacity > MAXIMUM.number);
`MINUMUM.number`이 뭔가 어색한데요.. 필드값을 `value`로 하는게 더 나을까요? 이 부분은 반영하시지 않으셔도 됩니다~

2022-08-22 18:28 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/member/domain/Member.java
> +        this.userName = name;
userName과 name이 혼용되어 사용되고 있는 것 같아요! 소소하지만 userName으로 바꾸는건 어떨까요?..ㅎ

2022-08-22 18:28 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/member/domain/Member.java
> +        userName.update(GHOST_NAME);
update 메소드로 바꾸니 훨씬 명확한 거 같아요~

2022-08-22 18:28 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/member/domain/Password.java
> +    private static final String PASSWORD_FORMAT = "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[~!@#$%^&*()+|=])[A-Za-z\\d~!@#$%^&*()+|=]{8,16}$";
종종 팀원들과 정규 표현식 관련해서 이야기를 나누었던 것 같아요.

누군가 코드를 읽는다고 가정했을 때, 이 정규표현식을 보고 어떤 표현식인지 빠르게 알 수 있을까요? 아니라면 이 부분에 대해서는 정규표현식을 사용하지 않거나 주석이 필요하지 않을까요?

2022-08-23 02:50 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
>      }
해당 의견은 무시하셔도 괜찮습니다!! 잘못생각했네여~ㅎ;;

2022-08-23 02:51 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
> +        validateTemplate((() -> isHost(member)), PARTICIPANT_LEAVE_HOST);
![image](https://user-images.githubusercontent.com/22176552/186058832-b8cd181f-214d-40c3-a48a-8e046bd592bb.png)

2022-08-23 15:20 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/member/domain/UserId.java
> +    }
넵 수정했습니다! UserId 는 현재의 정책상 수정하지 않도록 결정해서 지워둔 상태입니다!

2022-08-23 16:14 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/auth/service/AuthService.java
> +        Optional<Member> member = memberRepository.findByUserId(new UserId(userId));
Request DTO 를 Assembler 를 이용해 객체로 만드는 방식은 찬성합니다~ 예시로 들어주신 네이밍인 Member**Request**Assembler 도 요청으로 들어온 값(DTO) 를 내부에서 사용하는 값(객체)으로 바꾼다는 취지에서 좋은 것 같습니다. 

근데 리팩토링을 하면서 `validateUserNotExist(String value)` 가 `validateUserNotExist(UserId value)` 로 바뀌었는데요, 마지막으로 들어주신 예시에서는 파라미터로 `request.getUserId()` 받네요. 혹시 SignUpRequest 의 getter 에서 객체를 반환한다는 의미일까요?

***

서비스 로직이 길어진다는 문제는 사실 Member 보다는 Group 이 더 심각한데요, Group 에도 적용시키는 것은 어떤가요? Group 에도 똑같은 방식으로 한다면 Group 을 수정할 때에도 Group 을 받아와 서비스 계층에서는 간결한 대신에 도메인 내부에서 전부 꺼내써야한다는 점이 있습니다.

다음과 같은 로직을

```
    public void update(GroupName name, Member host, Category category, Capacity capacity, Duration duration, Deadline deadline,
                       Schedules schedules, String location, String description) {
        this.name = name;
        this.category = category;
        this.location = location;
        this.description = description;

        participants.update(capacity);
        calendar.update(schedules, duration, deadline);
        validateGroupIsInitialState(host);
    }
```

아래처럼 사용하게 됩니다. (아래 코드로 테스트를 돌려보진 않아 실제로 적용하면 일부 수정될 수는 있습니다..ㅎ)

```
    public void update(Group group) {
        name = group.name;
        category = group.category;
        location = group.location;
        description = group.description;

        participants.update(group.participants.getCapacity());
        calendar.update(group.calendar.getSchedules(), group.calendar.getDuration(), group.calendar.getDeadline());
        validateGroupIsInitialState(group.host);
    }
```

이프가 예시를 들어주신 것과 제가 제안한 것의 차이는, 예시는 Repository 를 이용해 바로 저장되는 값이기 때문에 도메인 내부에서 해체하는 등의 과정이 없다는 점입니다. 

일단 궁금한 점이 있어 적용하지는 않았습니다~

2022-08-23 16:30 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/calendar/Duration.java
> +    }
> 이러한 객체 생성은 Service에서 적용된 @Transactional(-> DB에 대한 제약)과는 달리
객체가 사라지지 않고 계속해서 메모리에 남게 되고 GC에 의해 지워지기를 기다립니다.

헉!! 😲 알려주셔서 감사해요 이프의 피드백은 배울 점이 많네요ㅎㅎ

2022-08-23 16:51 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
>      }
넵 알겠습니당 😁😁😁

2022-08-23 17:06 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/member/domain/UserId.java
> +    }
메서드가 호출된 순을 기준으로 하다보면 여러 곳에서 호출되는 메서드의 경우 위치가 애매하더라구요.. 이 부분은 개발자마다 방식이 다를것 같은데 방학 끝나면 다같이 회의해보는 것은 어떨까요?

2022-08-23 17:08 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/member/domain/UserId.java
> +            throw new MomoException(SIGNUP_INVALID_ID);
앗 에러 코드 관련해서는 이프가 리팩토링을 진행중인걸로 알아서(그러고보니 왜 이슈가 없죠..???ㅋㅋ 분명 리팩토링하는 모습을 본거같은데..) 네이밍은 수정하지 않았습니다! 의견 감사합니당

2022-08-23 17:09 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/member/domain/UserId.java
> +    }
이것도 방학이 끝나고 이야기 해볼까요? 다같이 회의할 정도로 심각한 문제는 아니지만 테이블 스펙이 달라지는거다보니 저 혼자 결정하기 부담스럽네요..ㅎㅎ

2022-08-23 17:10 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/auth/service/AuthService.java
> +        Password password = Password.encrypt(request.getPassword(), passwordEncoder);
이프의 도움이 많이 반영되었습니다 🤣

2022-08-23 17:21 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/auth/service/AuthService.java
> +            throw new MomoException(SIGNUP_ALREADY_REGISTER);
이 부분에 대해서는 의견이 다양하게 나뉠 것 같아요~ 일단 이전에 [이프와 얘기했던 내용](https://github.com/woowacourse-teams/2022-momo/pull/213#discussion_r940867039)을 공유드립니다!! 

요약하자면 ~FindService 는 특별한 로직이 없는 단순한 조회 메서드만을 관리하고, 이후 로직이 존재하는 조회 메서드가 중복적으로 발생한다면 추후 상의하자 입니다! 둘이 상의한 내용이기 때문에 다른 의견이 있으시다면 남겨주세요!

2022-08-23 17:26 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/service/dto/request/GroupRequest.java
> +    @NotNull
프론트에서 빈값을 보내주기로 약속하기도 했고, @NotNull 어노테이션을 이용해 부적합한 값은 검증했다고 생각합니다! 프론트에서 빈값을 보내주지 않더라도 잘못된 값(null) 이 들어온다면 예외가 발생합니다. null 이외의 잘못된 값은 지금은 생각나는게 없네요..🥲

2022-08-23 17:31 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/participant/domain/Participants.java
> +}
별도의 로직이 존재하지만 getter 의 일종으로 생각해서 만든 메서드입니다! 이것도 추후에 백엔드 팀원끼리 정해야할 컨벤션이지만, 일단 저의 방식은 getter 는 가장 하단에 두기 때문에 아래에 두었습니다!

2022-08-23 17:32 UTC, kyukong commented on backend/src/test/java/com/woowacourse/momo/participant/controller/ParticipantControllerTest.java
> +        fieldDeadline[index].set(deadline, date);
리플렉션.. 최고... 👍

2022-08-23 17:32 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/calendar/Schedules.java
> +
ㅋㅋㅋㅋ 혹시.. 저도 반대했었나요...? 🙄

2022-08-24 04:21 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/auth/service/AuthService.java
> +        Optional<Member> member = memberRepository.findByUserId(new UserId(userId));
> 근데 리팩토링을 하면서 validateUserNotExist(String value) 가 validateUserNotExist(UserId value) 로 바뀌었는데요, 마지막으로 들어주신 예시에서는 파라미터로 request.getUserId() 받네요. 혹시 SignUpRequest 의 getter 에서 객체를 반환한다는 의미일까요?

예시에 대한 설명이 부족했었네요. 원시값을 값객체로 감싸는 행위는 Request DTO의 Getter에서 곧바로 실행해버리고, 여러 값객체(또는 원시값)을 이용해서 Member나 Group과 같은 객체를 생성하는 로직은 Assembler에서 처리하는 것을 의미했어요.

---

> 서비스 로직이 길어진다는 문제는 사실 Member 보다는 Group 이 더 심각한데요, Group 에도 적용시키는 것은 어떤가요? Group 에도 똑같은 방식으로 한다면 Group 을 수정할 때에도 Group 을 받아와 서비스 계층에서는 간결한 대신에 도메인 내부에서 전부 꺼내써야한다는 점이 있습니다.

저번에 얘기나눴던 방식이네요!! 이 부분에 대해 고민을 해봤는데, 하나의 매개변수로 묶는 것보다는 사용되는 파라미터를 지정해서 사용하는 쪽이 좋다고 생각해요. 우선 `Group#update`를 실행하기 위해 Group 객체를 생성해야 한다는 점은, 해당 메서드를 사용하는 쪽에서 객체 생성 로직이 추가됨과 동시에 일회성 객체를 생성하게 되어요. 둘째 `Group#update`의 인터페이스가 `public void update(Group group)`이기 때문에, 사용하는 측에서 무엇을 업데이트하고자 하는 메서드인지 모르게 돼요. 앞선 생각일진 모르지만 개인정보 수정 방식과 같이 각각의 정보를 따로 수정할 수 있도록 요구사항이 변경된다면 처음 코드를 보는 팀원(신입)은 내부 로직을 분석해야만 해당 메서드가 무엇을 변경하는지 알 수 있고 메서드를 분리할 수 있을 거예요. 셋째 유콩이 언급하신 바와 같이 `Group#update` 내부 로직이 난잡해져요.

그래서 리팩터링한다면 아래와 같이 세 방식 중 마지막 형태로 진행할 듯 합니다.
```java
    // RequestAssembler를 사용하는 방식
    @Transactional
    public void update(Long hostId, Long groupId, GroupUpdateRequest request) {
        Group group = groupFindService.findGroup(groupId);
        Member host = memberFindService.findMember(hostId);

        GroupName groupName = GroupRequestAssembler.groupName(request);
        Capacity capacity = GroupRequestAssembler.capacity(request);
        Calendar calendar = GroupRequestAssembler.calendar(request);

        group.update(groupName, host, Category.from(request.getCategoryId()), capacity,
                calendar, request.getLocation(), request.getDescription());
    }
```
```java
    // RequestDto의 Getter에서 값객체를 반환하는 방식
    @Transactional
    public void update(Long hostId, Long groupId, GroupUpdateRequest request) {
        Member host = memberFindService.findMember(hostId);
        Group group = groupFindService.findGroup(groupId);
        group.update(request.getGroupName(), host, request.getCategory(), request.getCapacity(),
                request.getCalendar(), request.getLocation(), request.getDescription());
    }
```

```java
    // RequestDto의 Getter에서 값객체를 반환하는 방식 + 메서드 추출
    @Transactional
    public void update(Long hostId, Long groupId, GroupUpdateRequest request) {
        Member host = memberFindService.findMember(hostId);
        Group group = groupFindService.findGroup(groupId);
        validateMemberOwnsGroup(host, group);
        updateGroup(group, request);
    }

    private void updateGroup(Group group, GroupUpdateRequest request) {
        GroupName groupName = request.getGroupName();
        Category category = request.getCategory();
        Capacity capacity = request.getCapacity();
        Calendar calendar = request.getCalendar();
        String location = request.getLocation();
        String description = request.getDescription();
        
        group.update(groupName, calendar, capacity, calendar, location, description);
    }
```

2022-08-24 04:32 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Capacity.java
> +    }
그래도 `<=` 보다 `==` 가 맞는 것 같아요!!

2022-08-24 04:34 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/member/domain/UserId.java
> +            throw new MomoException(SIGNUP_INVALID_ID);
에러메시지 작업 현재 대기중입니다~ 작업하려면 전반적으로 검증로직을 세세하게 쪼개야 해서,
기다리고 있어요ㅎㅎ Merge 되면 작업분량 파악하고 이슈올리겠습니다~

2022-08-24 04:38 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/calendar/Schedules.java
> +
`@Embedded` 쓰기 싫어서 모두 반대했었죠 😅😅

2022-08-24 04:45 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Capacity.java
> +    }
`capaticy <= numberOfPeople` 맞지 않나요?? 받아온 참여자 수로 비교했을 때 수용인원이 그것보다 같거나 작으면 가득찼다.. 맞지않나요?

2022-08-24 04:46 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/Capacity.java
> +    }
ㅋㅋㅋㅋ 답변을 다니 수정되었군요! 혹시나 해서 `<=` 로 했는데 의미상 `==` 이게 맞긴 하겠네요 수정했습니다~!

2022-08-24 04:53 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/service/dto/request/GroupRequestAssembler.java
> +    }
입력하는 값의 타입과 반환되는 값의 타입이 정반대일 뿐, 역할을 같다고 생각했어요. 외부에서 사용된 값을 내부에서 사용하는 값으로, 내부에서 사용된 값을 외부에서 사용하는 값으로 변환해주는 역할이요. 

이전에 혼자 미션을 했을 때에는 해당 역할을 모두 Service 에게 줬었어요. 그때는 Group 처럼 복잡한 객체가 없었기 때문에 로직 자체는 괜찮았으나 여러 Service 에서 필요한 과정이 중복되더라구요. 복잡한 변환 로직을 분리하고, 여러 Service 에서 중복될 수 있는 코드를 묶어 관리하는 측면에서 좋다고 생각해요. 또한 객체 변환 역할을 Service 에 애매했었는데 별도의 객체를 생성해서 역할을 부여한다는 의미에서도 좋았습니당

2022-08-24 04:54 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/participant/domain/Participants.java
> +    public boolean isParticipant(Member member) {
좋습니다~~!!!

2022-08-24 04:57 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/calendar/Schedules.java
> +    public boolean isExistAnyScheduleOutOfDuration(Duration duration) {
`hasAnyScheduleOutOfDuration` 로 바꾸어봤는데 어떤가요?

2022-08-24 05:29 UTC, kyukong commented on backend/src/test/java/com/woowacourse/momo/group/domain/calendar/SchedulesTest.java
> +    }
바꾸는 김에 다른 테스트들도 바꾸어보았어요ㅎㅎ
- SchedulesTest
- DurationTest
- CapacityTest
- GroupTest

2022-08-24 05:37 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/auth/config/RefreshTokenAuthInterceptor.java
> +import static com.woowacourse.momo.global.exception.exception.ErrorCode.AUTH_INVALID_TOKEN;
사용되는 위치가 대부분 MomoException(`여기`) 내부이거나 메서드에서 매개변수로 전달받는 곳입니다. Exception 내에서 사용하는 경우 에러와 관련된 것임을 바로 알 수 있고, 매개변수로 받을 때에도 마찬가지라고 생각했어요. 이것은 에러 코드임을 나타내기 위해 `ErrorCode` 를 앞에 붙여 호출하는 것보다는 에러 코드의 이름을 맞추는 편이 좋다고 생각해 static 으로 선언해보았습니다..

2022-08-24 05:38 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/calendar/Deadline.java
> +    }
좋아요~~!!!

2022-08-24 05:39 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/group/GroupCapacityRange.java
> +        return (MINIMUM.number > capacity) || (capacity > MAXIMUM.number);
예시로 들어주신 것도 어색하기도 하고 값도 하나뿐이니 value 가 좋을 것 같네요!

2022-08-24 05:44 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/member/domain/Password.java
> +    private static final String PASSWORD_FORMAT = "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[~!@#$%^&*()+|=])[A-Za-z\\d~!@#$%^&*()+|=]{8,16}$";
개인적으로 코드에 주석을 남기는 것을 안좋아하는 입장으로써, 이 부분은 모든 팀원들의 동의가 필요하다고 생각해요. 저뿐만 아니라 주석에 관해서는 다들 생각이 다르니까요. 

일단 정규식에 관해서 주석을 남기는 것은 동의합니다! 해당 정규식이 어떤걸 검증하는지 알려면 정규식 마스터거나, 테스트코드를 보거나, 에러코드 메시지를 봐야하는데 메시지는 아무래도 프론트에게 알려주기 위함이니 100%의 내용을 포함하기 어렵죠. 다른 분들은 어떻게 생각하시나요?

@sinb57 @Seongwon97

2022-08-24 06:17 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/auth/service/AuthService.java
> +        Optional<Member> member = memberRepository.findByUserId(new UserId(userId));
> 원시값을 값객체로 감싸는 행위는 Request DTO의 Getter에서 곧바로 실행해버리고, 여러 값객체(또는 원시값)을 이용해서 Member나 Group과 같은 객체를 생성하는 로직은 Assembler에서 처리하는 것을 의미했어요.

이프가 말씀하시던게 `엔티티가 아닌 값객체에 한해서는 Request DTO 에서 반환하자` 이거 맞나요? 드디어 이해했습니다! 😄 DTO 에서 값객체를 반환해준다면 로직은 간결해지겠지만.. 값객체라고 해서 값을 보유하기만 하는 역할을 하는게 아닌 일부 로직이 있어서 고민이네요. 편의성을 위해서라면 불편을 감수하고 도메인을 노출시키지 않는 것이 좋지 않을까요?

일단 Request DTO 에서 값객체를 반환하는 과정을 제외하고, 메서드는 분리하였습니다!

2022-08-24 06:31 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
> +        Member host = memberFindService.findMember(hostId);
1단계가 서비스 계층에서 처리되어도 된다고 판단한 기준은 이미 서비스 계층에서 Group 과 Member 가 생성된 상태에서, Group 의 내부로 보낸 후 주최자인지 검증하기 때문일까요? 

서비스 계층에서 검증을 한다고 하더라도, 결국은 도메인 로직을 호출합니다. `group.isHost(host)` 등과 같은 형식으로요. 어차피 도메인 로직을 불러와서 사용한다면 도메인 로직을 서비스에서 처리하는 것보다는 도메인으로 보내서 한번에 처리하는 것이 좋지 않을까요?

2022-08-24 06:43 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
> +        Schedules schedules = GroupRequestAssembler.schedules(request.getSchedules());
매개변수의 수를 줄일 수 있는 것이 너무 좋지만.. [이것](https://github.com/woowacourse-teams/2022-momo/pull/316#discussion_r953326223)과 유사한 방법인것 같습니다. 특정 객체를 수정할 때 동일한 타입의 객체를 받아올지, 수정할 값에 한해서만 받아올지 하나로 통일하는 것이 좋아보입니다.

아래는 Calendar 객체를 받아오는 코드를 적용했을 때의 예시입니다.

**_Group#update_**
```java
    public void update(GroupName name, Member host, Category category, Capacity capacity, Calendar calendar,
                       String location, String description) {
        validateGroupIsInitialState(host);
        this.name = name;
        this.category = category;
        this.location = location;
        this.description = description;

        participants.update(capacity);
        calendar.update(calendar);
    }
```

**_Calendar#update_**
```java
    public void update(Calendar calendar) {
        validateIsBeforeStartDuration(calendar.duration, calendar.deadline);
        validateSchedulesAreInDuration(calendar.schedules, calendar.duration);
        schedules.change(calendar.schedules);
        duration = calendar.duration;
        deadline = calendar.deadline;
    }
```

아니면 Group 에서는 Calendar 객체로 받고 내부에서 해체 후 update 하는 것을 말씀하신걸까요?

**_Group#update_**
```java
    public void update(GroupName name, Member host, Category category, Capacity capacity, Calendar calendar,
                       String location, String description) {
        validateGroupIsInitialState(host);
        this.name = name;
        this.category = category;
        this.location = location;
        this.description = description;

        participants.update(capacity);
        calendar.update(calendar.getSchedules(), calendar.getDuration(), calendar.getDeadline());
    }
```

**_Calendar#update_** -> 현재 유지
```java
    public void update(Schedules schedules, Duration duration, Deadline deadline) {
        validateIsBeforeStartDuration(duration, deadline);
        validateSchedulesAreInDuration(schedules, duration);
        this.schedules.change(schedules);
        this.duration = duration;
        this.deadline = deadline;
    }
```

2022-08-24 06:47 UTC, kyukong commented on backend/src/test/java/com/woowacourse/momo/group/service/GroupFindServiceTest.java
> +        momo = memberRepository.save(new Member(new UserId("momo"), password, new UserName("momo")));
리뷰가 많아.. 급하게 수정하다보니... 기계적으로 처리했던 부분이 있는것 같네요 😭 저 역시 전에 얘기했던 바와 마찬가지로 테스트를 위한 생성자는 완전 찬성합니다. 해당 생성자가 비즈니스 로직에 반하는 내용이 아니라면요! (예로 capacity 를 -1 로 두어도 예외가 발생하지 않는 경우는 만들면 안되겠죠.)

여러 타입에 관한 생성자를 열어두어 생성자 사용의 편의성을 높이자는 의견 완전 동의합니다!! 그리고 피드백으로 집어주셔서 감사해요

2022-08-24 09:47 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/auth/service/AuthService.java
> +        Optional<Member> member = memberRepository.findByUserId(new UserId(userId));
> 값객체라고 해서 값을 보유하기만 하는 역할을 하는게 아닌 일부 로직이 있어서 고민이네요. 편의성을 위해서라면 불편을 감수하고 도메인을 노출시키지 않는 것이 좋지 않을까요?

로직이 있다하더라도 값객체로써 불변을 보장하기 때문에 DTO가 값객체를 반환하는 것이 괜찮다고 생각해요.
그리고 Controller Layer에서 값객체를 가져다 사용하는 것을 방지하고자 한다면,
Controller Layer와 Service Layer의 DTO를 분리하면 돼요

2022-08-24 10:12 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
> +        Member host = memberFindService.findMember(hostId);
첫째, 모임을 수정하거나 삭제하거나 그 어떠한 로직을 수행하든 가장 먼저 이뤄져야 하는 것은 `Group의 주최자가 Member가 맞는지` 검증하는 것이라고 생각해요. 그렇지 않으면 모임 수정/삭제를 진행하기 위해 값객체들의 생성에 의해 리소스가 낭비되고, (Transactional 특성상) 짧은 시간이어도 DB 테이블 접근이 lock 되어버리고 이러한 시간은 무수한 요청속에서 (짧은시간 x 요청횟수)만큼이나 긴 시간 지속되어 서비스의 성능을 저하시킵니다. (단일 DB서버는 유독 심함)

둘째, 도메인 관점에서 `Group#update` `Group#delete`가 인터페이스 상, Host를 매개변수로 요구하는 이유를 이해하지 못하겠어요. 서비스는 도메인의 여러 행위를 하나로 묶어서 사용하는 Layer라고 생각해요. 이는 여러 도메인을 묶을 수도 있지만 하나의 도메인에 대해 여러 행위를 호출하여 묶는 것 또한 의미해요. 따라서 Host가 모임의 주최자인지 확인하는 검증 로직을 도메인 내부에 숨겨놓을 필요가 없다고 생각해요. 오히려 이러한 메서드를 순서대로 배치해서 사용하는 서비스 쪽에 두어야 로직 파악이 쉽지 않을까요

2022-08-24 10:15 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/service/dto/request/GroupRequest.java
> +    @NotNull
사용자가 입력을 하지 않았기에 프론트에서 "" 값을 보내는 행위는 백엔드에서 검증할 수 있는 범위를 벗어났다고 생각해요. 사용자의 입력 유무는 프론트에서만 확인가능하니까요. 따라서 백엔드에서는 `@NotNull` 처리만 해주면 된다고 생각해요.

2022-08-24 10:17 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
> +        Schedules schedules = GroupRequestAssembler.schedules(request.getSchedules());
두번째 방법 `Group 에서는 Calendar 객체로 받고 내부에서 해체 후 update 하는 것`을 의미했습니다~

2022-08-24 10:18 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/calendar/Schedules.java
> +    public boolean isExistAnyScheduleOutOfDuration(Duration duration) {
아주 좋습니다~!! 의미가 명확하네요ㅎ

2022-08-24 10:20 UTC, sinb57 commented on backend/src/test/java/com/woowacourse/momo/group/service/GroupFindServiceTest.java
> +        momo = memberRepository.save(new Member(new UserId("momo"), password, new UserName("momo")));
완전 좋습니다~!!

2022-08-24 10:30 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/member/domain/Password.java
> +    private static final String PASSWORD_FORMAT = "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[~!@#$%^&*()+|=])[A-Za-z\\d~!@#$%^&*()+|=]{8,16}$";
다른 해결 방법이 없다면 주석을 남기는 것에 적극 동의합니다!!

2022-08-24 12:07 UTC, sinb57 reviewed
유콩~ 변경점이랑 코멘트 모두 확인했어요!! 엄청 깔끔한 코드가 되었네요ㅎ

아래의 Conversation들이 해결되면 바로 approve 하겠습니다~!!

[discussion_r953588471](https://github.com/woowacourse-teams/2022-momo/pull/316#discussion_r953588471)
[discussion_r953612117](https://github.com/woowacourse-teams/2022-momo/pull/316#discussion_r953612117)
[discussion_r953707998](https://github.com/woowacourse-teams/2022-momo/pull/316#discussion_r953707998)
[discussion_r953616827](https://github.com/woowacourse-teams/2022-momo/pull/316#discussion_r953616827)

2022-08-25 02:56 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/auth/config/RefreshTokenAuthInterceptor.java
> +import static com.woowacourse.momo.global.exception.exception.ErrorCode.AUTH_INVALID_TOKEN;
확인했습니다~ MomoException 클래스에서는 일반 예외 클래스와는 다르게 ErrorCode 클래스를 사용합니다. 일반 예외 클래스에서는 생성자의 매개변수에 에러 메시지가 들어가게 되요. 저희야 MomoException에서 ErrorCode 클래스를 사용한다고 알고 있지만, 처음 코드를 보는 입장에서는 해당 클래스에서 ErrorCode 클래스를 사용한건지, 상수로 선언해 둔건지 혼란스러울 수도 있다고 생각합니다~

2022-08-25 04:22 UTC, nbalance97 approved these changes
유콩 리팩토링 하느라 고생 많으셨습니다ㅎㅎ

저는 이만 Approve 할게요. 즐거운 방학 보내세요~

2022-08-25 11:53 UTC, kyukong commented
이프! 미리 말씀드렸던 내용 정리해둡니다..ㅎㅎ..
이프가 마지막으로 남겨주신 코멘트 중에서 일부는 적용했고 일부는 남겨두었습니다...맡아주신다고 해주셔서 감사해요 😊

### 적용한 내용
- [특정 기능에 대해 모임의 주최자인지 확인하는 로직을 서비스 계층으로 이동](https://github.com/woowacourse-teams/2022-momo/pull/316#discussion_r953612117)
- [Group 수정 시 Calendar 객체로 받아오도록 변경](https://github.com/woowacourse-teams/2022-momo/pull/316#discussion_r953616827)

### 아직 적용하지 않는 내용
- [요청 DTO 에서 값객체 반환 (+ 계층 간 DTO 분리?)](https://github.com/woowacourse-teams/2022-momo/pull/316#discussion_r953588471)
- [Assembler 제거](https://github.com/woowacourse-teams/2022-momo/pull/316#discussion_r953707998)

2022-08-25 11:58 UTC, sinb57 approved these changes
유콩~ 방학인데 쉬지도 못하고 리팩토링하시느라 정말정말 고생 많으셨어요!! 이만 Approve 드리겠습니다~ 다음은 제가 이어서 리팩토링 진행하겠습니다~!!!

2022-08-25 17:04 UTC, Seongwon97 approved these changes
유콩 방학기간중에도 수고 많으셨습니다
저도 approve하겠습니다!!
수고하셨어요👍👍👍

2022-08-26 00:18 UTC, merged