Feature #320
woowacourse-teams/2022-momo pull request #323
Opened 2022-09-04 17:39 UTC by sinb57

## 🌟 구현 기능
- [x] Group 패키지로 Participant 패키지 병합
- [x] Group Request Dto 계층 분리
- [x] Group 테스트픽스처 활용
- [ ] 예외처리 분리

## 비고
- [ ] MemberServiceTest#deleteAndLeave 테스트 통과 -> (`@Transactional`에 의해 delete 쿼리 동작 x)

https://github.com/woowacourse-teams/2022-momo/issues/320

2022-09-06 04:32 UTC, sinb57 commented
이해하기 어려운 로직이나 명칭들이 있으면 지적해주세요!!
가독성과 유지보수 측면으로 좋은 의견, 적극 수용하겠습니다~!!

2022-09-07 06:56 UTC, Seongwon97 requested changes
남은 코드리뷰는 빠르게 미션 진행후..다시 진행해보겠습니다

2022-09-07 06:56 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/global/exception/exception/ErrorCode.java
> +    GROUP_NOT_EXIST(HttpStatus.NOT_FOUND.value(), "GROUP_ERROR_001", "존재하지 않는 모임입니다."),
```java
    VALIDATION_ERROR(400, "V_001", "잘못된 요청입니다."),
    INTERNAL_SERVER_ERROR(500, "S_001", "내부 서버 오류입니다."),

    NOT_EXIST(400, "M_001", "멤버가 존재하지 않습니다."),
    DELETED(400, "M_002", "탈퇴한 멤버입니다."),
    DELETED_EXIST_IN_PROGRESS_GROUP(400, "M_003", "진행중인 모임이 있어 탈퇴할 수 없습니다."),
    WRONG_PASSWORD(400, "M_004", "비밀번호가 일치하지 않습니다."),
    NAME_SHOULD_NOT_BE_BLANK(400, "M_005", "사용자의 이름이 빈 값입니다."),
    NAME_MUST_BE_VALID(400, "M_006", "사용자의 이름이 30자를 넘습니다."),
    PASSWORD_SHOULD_NOT_BE_BLANK(400, "M_007", "패스워드가 빈 값입니다."),
    PASSWORD_PATTERN_MUST_BE_VALID(400, "M_008", "패스워드는 영문자와 하나 이상의 숫자, 특수 문자를 갖고 있어야 합니다."),
    ENCRYPTED_PASSWORD_MUST_NOT_UPDATE(400, "M_009", "암호화된 패스워드는 수정할 수 없습니다."),
    ID_SHOULD_NOT_BE_BLANK(400, "M_010", "사용자의 아이디가 빈 값입니다."),
    GOOGLE_ID_SHOULD_BE_IN_EMAIL_FORMAT(400, "M_011", "구글 아이디가 이메일 형식이 아닙니다."),
```

2022-09-07 09:49 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/participant/Participants.java
> +    @ManyToOne
테스트가 깨져서 반영하지 않았습니다!! 

<img width="1173" alt="스크린샷 2022-09-07 오후 6 49 20" src="https://user-images.githubusercontent.com/22176552/188848457-1aeba1cb-d77b-469e-85a3-a54b6230c51a.png">

2022-09-07 09:50 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/participant/Participants.java
> +            cascade = {CascadeType.PERSIST, CascadeType.REMOVE})
반영했습니다~!!

2022-09-07 09:59 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/participant/Capacity.java
> +    }
반영했습니다~! 코드가 깔끔해지네요 ㅎ

2022-09-07 10:02 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/controller/GroupHostController.java
> +                .body(groupIdResponse);
동의합니다!! 우선 반영했습니다~!

2022-09-07 10:02 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/Group.java
> +
값객체를 쓰니 Builder의 필요성이 없어지더라구요ㅎ

2022-09-07 10:03 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/GroupName.java
> +    }
이 부분은 전체 회의가 필요한 부분이어서, 천천히 얘기나눠봐요~!

2022-09-07 10:04 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/member/domain/UserId.java
> +
저 또한 통일해야한다는 것에 동의합니다!! 다만, 현재 PR에서 처리하기엔 이미 Changed Files 가 너무 많아서, 별도의 PR을 통해 진행하는 것이 좋다고 생각해요~!!

2022-09-07 10:04 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/global/exception/exception/ErrorCode.java
> +    GROUP_NOT_EXIST(HttpStatus.NOT_FOUND.value(), "GROUP_ERROR_001", "존재하지 않는 모임입니다."),
금일 팀원들과 상의한 내용에 맞춰 GroupErrorCode를 수정했습니다~!!

2022-09-10 14:36 UTC, Seongwon97 requested changes
이프~
반영해주신 코드와 함께 프로젝트 코드를 전반적으로 살펴보며 몇가지 리뷰를 추가했습니다!!

이번 리펙터링 내용과 상관이 없는 내용도 존재하지만 대대적인 리펙터링 작업인만큼 귀찮지만 않으시다면 바로 반영해도 괜찮을 것 같습니다!!

수고하셨습니다 이프🚀

2022-09-10 14:36 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/global/exception/exception/ExceptionMessage.java
> +}
현재 사용되지 않는 클래스라 제거해주셔도 될 것 같습니다!

2022-09-10 14:36 UTC, Seongwon97 commented on backend/src/test/java/com/woowacourse/momo/acceptance/group/GroupDeleteAcceptanceTest.java
> +        모임을_삭제한다(hostAccessToken, groupId)
현재 인수 테스트 클래스들에 `@SuppressWarnings("NonAsciiCharacters")`이 붙어있지 않아서 인텔리제이에 아래와 같이 경고창이 계속 뜨고있어요!

번거로운 작업이지만 경고 표시를 하지 않는 어노테이션 추가 부탁드립니다😭😭

![image](https://user-images.githubusercontent.com/57744251/189487114-b1d2a887-6a32-43fe-8825-b505fc16ce96.png)

2022-09-10 14:41 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/participant/Participant.java
>  @Getter
이것도 테스트 2개가 추가로 깨지긴해서..수정이 잘 안된다면 앞서 남긴 Group과 Host의 연관관계랑 같이 연휴 끝나고 수정해봅시당😁

2022-09-10 14:44 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/participant/Capacity.java
> +        CapacityRange.validateCapacityIsInRange(value);
동의합니다!! 저 또한 작업하면서 CapacityRange의 필요성에 의문이 생겼거든요! 이번에 Capacity로 통합시키겠습니다

2022-09-10 15:01 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/participant/Participants.java
> +    }
매번 DB에 쿼리를 요청하는 것은 문제가 될 수 있지만, JPA 특성상 영속성컨텍스트에 캐시되어 있는 값을 재사용하게 되므로 성능에 영향을 줄 수준의 쿼리가 요청된다고 판단하지 않았습니다. 오히려 렉스가 제시한 `+1`도 처음엔 고려해봤지만, `1`에 대한 의미부여가 쉽지 않아서 시도하지 않았습니다.

2022-09-10 15:02 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/participant/Participant.java
>  @Getter
https://github.com/woowacourse-teams/2022-momo/pull/323#discussion_r964631356
이와 같은 현상이 발생해서 반영하지 않았습니다.

2022-09-10 15:05 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/calendar/Schedules.java
> +@ToString(includeFieldNames = false)
어..음.. 어떻게 할까요??ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
Intellij가 하라는대로 반영해보니까 @Exclude 어노테이션이 붙으면서 setter가 생기네요~~~하핳
![image](https://user-images.githubusercontent.com/22176552/189489332-76814464-e632-4a64-9477-e7a87181f251.png)

다시 처음대로 `public String toString()` 일일히 선언할까요??

2022-09-10 15:09 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/service/request/GroupFindRequest.java
> +    }
boolean형 값에 대한 getter인데, lombok에 의해 선언된 getter는 `is + 변수명`으로 되어있습니다.
때문에 아래의 첫문장과 같이 사용이 되는데, `is + boolean명`은 자연스럽지 않다고 판단하여 getter를 직접 선언했습니다.
```java
 .and(groupSpecification.orderByDeadline(request.isOrderByDeadline())); // lombok에 의해 선언된 getter
 .and(groupSpecification.orderByDeadline(request.orderByDeadline()));   // 직접 선언한 getter
```

2022-09-10 15:20 UTC, kyukong requested changes
안녕하세요 이프!! 대규모 리팩토링 진행하시느라 수고많으셨습니다 😄
파일 체인지 수에 비해서 리뷰가 많이 없네요 😓
리뷰에 대한 답변을 주고받으면서 천천히 추가하겠습니다!

2022-09-10 15:20 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/controller/GroupSearchController.java
> +                                                                    @ModelAttribute GroupFindRequest groupFindRequest) {
여기는 Controller 용 DTO 를 따로 만들지 않고 Service 의 DTO 를 사용하셨는데 이유가 있을까요?

2022-09-10 15:20 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupFindService.java
>          Pageable pageable = PageRequest.of(request.getPage(), DEFAULT_PAGE_SIZE);
이건 이번에 수정된 사항은 아니지만 의견 남겨둡니다!! 이 메서드가 findGroups 인데 다른 public 메서드도 findGroups 가 있더라구요. 비슷한 기능을 하는 메서드를 상황에 따라 나눈게 아닌 그냥 다른 메서드라서 헷갈려요. 혹시 `findGroupsWithWhereQuery` 혹은 `findGroupsWithCondition` 등으로 바꾸는건 어떨까요?

2022-09-10 15:20 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/service/specification/GroupAttribute.java
>  public enum GroupAttribute {
너무 좋네요~~!!! 😄👍

2022-09-10 15:20 UTC, kyukong commented on backend/src/test/java/com/woowacourse/momo/acceptance/RestHandler.java
> +    @Value("${acceptance.show}")
크으으.. 너무 좋네요 😣 이프의 테스트코드는 정말 갈수록 깔끔해져서 기분이 좋네요

2022-09-10 15:20 UTC, kyukong commented on backend/src/test/java/com/woowacourse/momo/acceptance/RestHandler.java
> +@Component
테스트에서 사용하는 객체를 빈 객체로 만든 이유가 있을까요?

2022-09-10 15:20 UTC, kyukong commented on backend/src/test/java/com/woowacourse/momo/fixture/GroupFixture.java
> +        fieldDeadline.set(calendar, DeadlineFixture.newDeadline(-pastDays));
리팩토링 하면서 매번 인덱스의 값을 수정했었는데..ㅋㅋㅋ 너무 깔끔해졌군요!!

2022-09-10 15:22 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/service/response/GroupResponseAssembler.java
>  @NoArgsConstructor(access = AccessLevel.PRIVATE)
#### 반영 성공
- `GroupIdResponse`는 렉스가 제시해주신대로 GroupFixture와 함께 수정했습니다.

#### 반영 보류
- `GroupResposneAssembler`는 static 메서드로 구성된 util성 클래스이므로, 기본생성자를 private으로 지정하여 불필요한 인스턴스 생성을 방지하고자 했습니다.

#### 반영 실패
- `ScheduleResponse`는 빈생성자가 존재하지 않으면, 여러 인수테스트에서 에러가 발생합니다.
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.woowacourse.momo.group.service.response.ScheduleResponse` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"date":"2022-09-13","startTime":"10:00:00","endTime":"12:00:00"}"; line: 1, column: 2]
```

- `MemberResponse`, `CategoryResponse`, `LoginResponse` 역시 위와 동일한 Jackson 에러가 발생합니다.

2022-09-10 15:23 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/participant/Participants.java
> +    public Participants(Member host, Capacity capacity) {
이미 주최자가 포함되어 있군요!! 제가 꼼꼼히 못봤습니다 넘어가주세요~~~!!! 😭

2022-09-10 15:27 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/participant/Participants.java
> +    @JoinColumn
아앗 리팩토링과정에서 누락됐네요!! 지적 감사합니다~!

2022-09-10 15:32 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/participant/Participants.java
> +    @JoinColumn
전 기본적으로 제공하는 기능이기 때문에 생략해도 된다고 생각합니다!! 테이블의 정보이기 때문에 엔티티 객체에서는 없어도 괜찮을것 같습니당

2022-09-10 15:37 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/controller/GroupHostController.java
> +                .body(groupIdResponse);
저는 평소에도 변수 추출을 잘 하지 않는 편이기는 한데..ㅋㅋ 특히나 Controller 에서는 더더욱 변수 추출은 하지 않아도 된다고 생각해요!! 해당 값이 어떤 값인지의 이름이 중요한 곳도 아니고 재사용도 안하니까요!

2022-09-10 15:40 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/participant/Participants.java
> +    }
저도 `+1` 하는 것은 데이터가 저장되어 있는 것을 넘어가고 임의로 지정한다는 느낌이 강해서 현행유지가 좋을것같아요!!

2022-09-10 15:43 UTC, sinb57 commented on backend/src/test/java/com/woowacourse/momo/acceptance/group/GroupDeleteAcceptanceTest.java
> +        모임을_삭제한다(hostAccessToken, groupId)
오 윈도우에선 표시가 안되는데 맥에서는 경고 표시가 뜨나보네요!!
요청하신대로 인수테스트코드에 `@SuppressWarnings("NonAsciiCharacters")` 선언해두었습니다~
`fixture/calendar/`를 사용하는 테스트코드에도 동일한 이슈가 있을 것 같은데 반영 범위가 커서 우선 놔뒀습니다.

2022-09-10 15:44 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/global/exception/exception/ExceptionMessage.java
> +public interface ExceptionMessage {
ㅎㅎ,, 에러코드 변경사항 적용하다보니 안지웠네요~ 지웠습니다!!

2022-09-10 15:44 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/global/exception/exception/GlobalErrorCode.java
> +    VALIDATION_ERROR(HttpStatus.BAD_REQUEST.value(), "VALIDATION_ERROR_001", "잘못된 요청입니다."),
넵~ 아직 프론트랑 협의되지 않은 부분이어서 축약하지않고 원본 그대로 사용하고 있어요!!

2022-09-10 15:48 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/participant/Participants.java
> +    public Participants(Member host, Capacity capacity) {
`getPaticipants()`에서 호스트를 포함한 총 참여자를 반환하고 `getSize()`에서 총 참여자 인원 수를 반환하므로
결론적으로 `getSize`는 호스트가 포함된 전체 참여 인원이 됩니다~!


```java
    public List<Member> getParticipants() {
        List<Member> members = participants.stream()
                .map(Participant::getMember)
                .collect(Collectors.toUnmodifiableList());

        return Stream.of(List.of(host), members)
                .flatMap(Collection::stream)
                .collect(Collectors.toUnmodifiableList());
    }
```

2022-09-10 15:50 UTC, sinb57 commented on backend/src/test/java/com/woowacourse/momo/acceptance/RestHandler.java
> +@Component
`@Value`를 통해 값을 주입받기 위해서는 RestHandler 또한 `@Value`와 동일한 수준으로 스프링에 의해 관리되어야 했어요!!

2022-09-10 15:51 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/controller/GroupSearchController.java
> +                                                                    @ModelAttribute GroupFindRequest groupFindRequest) {
Controller DTO와 동일한 구성이 되기 때문에 우선 Service DTO만 놔뒀는데,, 고민입니다.
일관성을 위해 Controller와 Service를 분리할까요??

2022-09-10 15:53 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/participant/Participants.java
> +    private final List<Participant> participants = new ArrayList<>();
CascadeType.REMOVE를 설정하지 않아도 되는 이유는, 애당초 참여자가 존재하면 모임을 삭제할 수 없기 때문인가요??

2022-09-10 15:55 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/controller/GroupHostController.java
> +public class GroupHostController {
강조하는 느낌이 들었다면 의도한대로 느끼신거예요!! Controller도 Service도 여러개가 존재하다보니 행위에 초점을 맞춰 구체화하여 구분지어야 할 필요성을 느꼈어요. 하나로 합치기에는 많은 책임을 앉고서 광범위한 객체가 되니까요

2022-09-10 16:05 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/controller/param/GroupParam.java
> +public class GroupParam {
Controller 계층에는 존재하지 않는 Deadline과 Schedules 에 대한 DTO가 Service에는 존재한다는 점에서 가장 큰 차이를 느낄 수 있습니다. Service 계층은 도메인 구조와 흡사하게 DTO를 구성할 수 있고 Controller 계층은 API 요구사항에 맞는 DTO 구조를 구성함으로써, API 변경에 더이상 Service 계층이 영향을 받지 않습니다.

또한 Service 계층의 DTO가 도메인 구조와 흡사해졌기 때문에, 실제 프로덕션 코드에서는 큰 이점을 느끼지 못하지만 테스트 코드에서는 도메인 픽스처의 활용이 극대화되었으며 Service 테스트에 이를 적극적으로 활용할 수 있게 되었습니다.

---

`~Param` 명칭에 대해 고민이 많았는데요. Controller 계층과 Service 계층의 DTO를 모두 `~Request`라고 이름지으면 혼란을 야기할 것이 분명했기 때문에 분리할 필요가 있었습니다. 여러 게시글을 조사해봤는데 `Query / Command`라는 명칭도 존재하지만 바로 Pass~(Nope!!). 고민 끝에 `~Param`을 떠올렸고, `GET 파라미터, POST 파라미터`라는 명칭에서 영감을 얻어 Controller 계층에 `~Param`을, Service 계층에 `~Request`를 부여했습니다.

2022-09-10 16:07 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupManageService.java
> +public class GroupManageService {
GroupService라는 네이밍이 지나치게 포괄적이라 생각했어요!! 이전부터 몇차례 얘기를 꺼내곤 있지만 한번 다같이 상의해보면 좋아보여요! 개인적으론 아래의 코멘트와 같이 생각하고 잇어요

2022-09-10 16:09 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupFindService.java
>          Pageable pageable = PageRequest.of(request.getPage(), DEFAULT_PAGE_SIZE);
헷갈린다는 점 동의합니다ㅠㅜ 다만 해당부분은 `GroupFindService`와 `GroupSearchService(임시)`를 병합하는 것이 최우선이기 때문에 보류할게요ㅜ 해당 부분의 리팩토링은 모두의 힘이 필요해요~~(굉장히 엄청난 녀석이예요,,)

2022-09-10 16:11 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/controller/GroupHostController.java
> +                .body(groupIdResponse);
이번 프젝을 하면서 많이 느끼는 것이 있다면, 진짜~ 개개인의 스타일은 달라요ㅋㅋㅋㅋㅎㅎ
그래서 정말 가독성을 해치지 않는 점에서는 스타일에 연연치 않고 넘어가려고 해요~
저는 아무거나 좋습니다~ 상의하고 알려줘요ㅎㅎ

2022-09-13 01:21 UTC, nbalance97 approved these changes
다른분들이 리뷰 잘 남겨주셔서 네이밍 관련된 부분만 리뷰 남겨드리는 것 같네요

고생하셨습니다~

2022-09-13 01:28 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/participant/Capacity.java
> +    public boolean isUnder(int numberOfPeople) {
`isSmallThan`으로 변경했슴다~~ㅎㅎ

2022-09-13 01:30 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/service/ParticipantService.java
> +        group.leave(member);
동의합니다!! 다른 팀원들과 함께 상의하여 적절한 네이밍을 부여하겠슴다~~
@Seongwon97 @kyukong 의견주세요~

2022-09-13 04:09 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/participant/Participants.java
> +    @ManyToOne
기능 개발 후 성능 최적화 이슈를 파서 한번 수정해봅시당

2022-09-13 05:00 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/controller/GroupHostController.java
> +                .body(groupIdResponse);
# 추출 확정👨🏻‍⚖️

2022-09-13 05:29 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/participant/Participants.java
> +    @JoinColumn
# 명시하는거로 확정 👨🏻‍⚖️

2022-09-13 05:32 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/service/request/GroupFindRequest.java
> +    }
# 유지 확정 👨🏻‍⚖️

2022-09-13 05:37 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/participant/Participants.java
> +    private final List<Participant> participants = new ArrayList<>();
# `CascadeType.REMOVE` 삭제 확정 👨🏻‍⚖️

2022-09-13 08:50 UTC, Seongwon97 approved these changes
# 🦸🏻‍♂️
수고 많으셨습니다👍
이제 기능 개발 합시다

2022-09-13 08:51 UTC, kyukong approved these changes
오랜 기간동안 직접 마주보고 회의를 하니 조금 힘들긴해도 오히려 빨리 끝났네요...!!
리팩토링하는 범위가 생각보다 컸는데 잘 해주셔서 감사합니다 😄👍
고생하셨어요~!

2022-09-13 10:44 UTC, merged