[BE] 조회로직 Specification(Criteria) -> QueryDsl 변경
woowacourse-teams/2022-momo pull request #339
Opened 2022-09-15 10:25 UTC by Seongwon97

## Issue

- #332 

## 🌟 구현한 기능
Specification(Criteria)를 이용한 기존의 조회로직을 QueryDsl로 변경

2022-09-16 08:34 UTC, kyukong requested changes
새로운 기술을 학습하고 도입하시느라 고생 많으셨습니다!!! 😊

가독성은 좋아졌지만 역시나 새로운 기술을 학습하는데는 시간이 걸리는군요 ㅠ.ㅠ
아직 QueryDSL 에 대해서 일부분만 학습해서 조금 더 찾아보면서 천천히 리뷰 추가하겠습니다!!

2022-09-16 08:34 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/infrastructure/querydsl/GroupSearchRepositoryImpl.java
> +package com.woowacourse.momo.group.infrastructure.querydsl;
`infrastructure.querydsl` 에서 infrastructure 는 생략해도 될 것 같습니당

2022-09-16 08:34 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/infrastructure/querydsl/GroupSearchRepositoryImpl.java
> +public class GroupSearchRepositoryImpl implements GroupSearchRepositoryCustom {
`GroupSearchRepositoryCustomImpl` 에서 돌아왔군요 😄

2022-09-16 08:34 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/infrastructure/querydsl/GroupSearchRepositoryImpl.java
> +    private Page<Group> findGroups(SearchCondition condition, Pageable pageable, Supplier<BooleanExpression> supplier) {
Supplier 객체 이름이 supplier 말고 의미를 나타내는 것은 어떤가요? where 절을 작성할 때 조건을 확인하니 whereCondition 같은 이름이요!

2022-09-16 08:34 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/search/GroupSearchRepositoryCustom.java
> +public interface GroupSearchRepositoryCustom {
QueryDSL 로 작성하고 싶은 부분만 별도로 분리해서 명세하여 구현하는군요! QueryDSL 구조가 재미있네요ㅎㅎ

2022-09-16 08:34 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupSearchService.java
>      }
그룹 상세정보 조회 로직은 `GroupManageService` 로 옮기는건 어때요? `findGroup` 외에 다른 모든 메서드는 `GroupSearchRepository` 만 사용하고 `findGroup` 에서만 `GroupFindService` 를 사용하고 있어요. `findGroup` 을 옮기면 의존 객체를 줄일 수도 있고 의미상으로도 잘 어우러질 것같아요.

- GroupSearchService : 그룹 리스트 검색 관련
- GroupManageService : 하나의 그룹 정보 관련

2022-09-19 02:15 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/infrastructure/querydsl/GroupSearchRepositoryImpl.java
> +    private Page<Group> findGroups(SearchCondition condition, Pageable pageable, Supplier<BooleanExpression> supplier) {
후보 추천해주세요ㅠㅠ
일단 제가 생각한건 mainCategory입니다😭

2022-09-19 05:09 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/infrastructure/querydsl/GroupSearchRepositoryImpl.java
> +package com.woowacourse.momo.group.infrastructure.querydsl;
추후 계속 고민해볼 예정..

2022-09-19 05:20 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/infrastructure/querydsl/GroupSearchRepositoryImpl.java
> +    private Page<Group> findGroups(SearchCondition condition, Pageable pageable, Supplier<BooleanExpression> supplier) {
# mainCondition으로 변경 완료🦸🏻‍♂️

2022-09-19 05:31 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupSearchService.java
>      }
# GroupModifyService로 이름 변경🦸🏻‍♂️

2022-09-19 05:31 UTC, nbalance97 approved these changes

2022-09-19 05:31 UTC, sinb57 approved these changes
👍👍👍

2022-09-19 05:32 UTC, kyukong approved these changes
😄👍

2022-09-19 05:36 UTC, merged