[BE] 도메인(Member, Group) 필드 제약조건 변경 및 검증로직 수정
woowacourse-teams/2022-momo pull request #385
Opened 2022-09-28 05:23 UTC by sinb57

## 🚀 기능 상세
- [ ] 서비스 로직에서 길이에 대한 검증 변경
- [ ] DB 테이블 제약조건 변경

## ✓ 모모 서비스 검증 조건
- [ ] 사용자 아이디 : `4` 자 이상 `50` 자 이하
- [ ] 사용자 이름 : `1` 자 이상 `20` 자 이하
- [x] 모임 제목 : `1` 자 이상 `50` 자 이하
- [ ] 모임 장소 : `1` 자 이상 `100` 자 이하
- [ ] 모임 설명 : `0` 자 이상 `1000` 자 이하

## ✓ DB 테이블 제약조건
- 사용자 이름 : `1` 자 이상 `36` 자 이하, Unique 조건 추가
  - 이전에 등록된 이름에 대한 Unique 처리 필요
  - 관련 PR : #379 

## 관련 이슈
https://github.com/woowacourse-teams/2022-momo/issues/381

2022-10-03 10:17 UTC, Seongwon97 approved these changes
수고하셨습니다 이프!
제약 조건의 변경 뿐만 아니라 검증 로직의 이상한 메서드 이름의 수정 등 여러 작업들도 해주셨네요!
👍👍👍

2022-10-03 10:17 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/Description.java
> +    private static final int MAXIMUM_LENGTH = 1000;
허허허 값 객체가 추가됐군요👀

2022-10-03 10:17 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/member/domain/UserId.java
> +    private static void validateNotBlank(String value) {
전반적으로 값 객체 검증 메서드 이름에 불필요하게 클래스 이름이 들어가 있었네요!
예리하게 수정해주셨네요

2022-10-03 10:17 UTC, Seongwon97 commented on backend/src/test/java/com/woowacourse/momo/auth/controller/AuthControllerTest.java
> +        SignUpRequest request = new SignUpRequest(" ".repeat(4), PASSWORD, NAME);
repeat메서드는 `" "`의 공백을 4번 반복해서 `"    "`가 만들어주는 것인가요?

2022-10-03 10:19 UTC, sinb57 commented on backend/src/test/java/com/woowacourse/momo/auth/controller/AuthControllerTest.java
> +        SignUpRequest request = new SignUpRequest(" ".repeat(4), PASSWORD, NAME);
맞습니다~ 길이 정책상 4자 이상의 값을 아이디에 할당하는데 길이 정책은 통과하나
빈값으로 구성된 경우를 필터링하기 위한 검증 테스트입니다!!

2022-10-03 15:16 UTC, nbalance97 requested changes
이프 안녕하세요~ 변경사항 잘 봤습니다!

간단한 요청사항(?) 남겨 드렸으니 확인 부탁드려요ㅎㅎ

2022-10-03 15:16 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/member/domain/Member.java
> +                .orElse("");
Optional을 활용하여 삭제유저 처리 좋네요👍

2022-10-03 15:16 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/member/domain/UserId.java
> +        validateNotEmailPattern(value);
검증 순서를 빈칸 유무 체크 -> 길이 검증 -> 이메일 검증 순으로 바꾸는건 어떨까요?

2022-10-03 15:16 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/member/domain/UserName.java
> +        validateNotBlank(value);
이부분도요! 😆

2022-10-03 15:16 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/Description.java
> +@EqualsAndHashCode
어디에서 쓰이는 녀석들인가요?

2022-10-04 04:40 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/domain/Description.java
> +@EqualsAndHashCode
VO 잖아요~~

2022-10-04 04:40 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/member/domain/UserId.java
> +        validateNotEmailPattern(value);
바꿨어여

2022-10-04 04:41 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/member/domain/UserName.java
> +        validateNotBlank(value);
바꿨어여 too

2022-10-04 04:44 UTC, nbalance97 approved these changes
고생하셨습니다 이프!ㅎㅎ

2022-10-04 05:15 UTC, kyukong approved these changes
완벽하네요~ 수고하셨습니다!! 👍👍👍

2022-10-04 05:17 UTC, merged