[BE] 모임의 일정이 설정한 날짜보다 하루 전날로 저장되는 현상 해결
woowacourse-teams/2022-momo pull request #416
Opened 2022-10-04 11:15 UTC by nbalance97

### 해결 방법
---
프로젝트의 전체 TimeZone을 UTC+09:00으로 설정해 주었다.

2022-10-04 11:26 UTC, Seongwon97 approved these changes
수고하셨습니다. 
다만 추가한 설정 코드를 config파일로 옮길 수 있다면 위치를 변경하는 게 좋을 것 같습니다!

2022-10-04 11:47 UTC, kyukong approved these changes
빠르게 해결되어 다행이네요 수고 많으셨습니다!!
(PR 메시지가 허전한거같아서 꾸며보았어요^^)

2022-10-04 13:00 UTC, sinb57 requested changes

2022-10-04 13:00 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/MomoApplication.java
> +
요렇게는 어떤가요?? 옆집 코드 가져와봤어요ㅋㅎㅎ [🐹](https://github.com/woowacourse-teams/2022-pickpick/blob/develop/backend/src/main/java/com/pickpick/config/TimeConfig.java)<-Click!!

2022-10-05 01:11 UTC, sinb57 approved these changes
깔꼼하세요!!! 👍👍

2022-10-05 01:14 UTC, merged