[BE] Group엔티티와 Favorite엔티티의 연관관계를 단방향으로 의존성 방향 수정
woowacourse-teams/2022-momo pull request #427
Opened 2022-10-05 08:53 UTC by Seongwon97

## ✨ Issue
- #417

## 🌟 리펙터링한 기능
Group엔티티와 Favorite엔티티의 연관관계를 단방향으로 의존성 방향 수정

## 🛠 상세 작업
- `Group`엔티티와 `Favorite`엔티티의 연관관계 단방향으로 수정
- `Like~`이름의 클래스를 `Favorite~`으로 수정
- `Favorite`객체가 갖던 `Group`, `Member`객체를 id로 수정

2022-10-06 17:09 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/favorite/domain/FavoriteRepository.java
> +    void deleteAllByMemberId(Long memberId);
오 확인해보니까 정말 그렇네요!! 
날라가는 쿼리를 확인해보고 수정했습니다!! 
역시 꼼꼼하시군요👍

2022-10-07 02:30 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/event/GroupDeleteEvent.java
> +public class GroupDeleteEvent extends ApplicationEvent {
```suggestion
public class GroupDeleteEvent {
```
Spring 4.2 부터 ApplicationEvent 상속 강제가 풀렸어요~!!와아아

https://docs.spring.io/spring-framework/docs/4.2.x/spring-framework-reference/htmlsingle/#context-functionality-events
<img width="90%" alt="스크린샷 2022-10-07 오전 11 28 18" src="https://user-images.githubusercontent.com/22176552/194453812-9bea0ee4-0107-46db-baa0-3db039433ab8.png">

ApplicationEventPublisher에 ApplicationEvent를 상속받지 않은 메서드를 지원하도록 오버로딩 메서드가 제공되었네요!!!
<img width="70%" src="https://user-images.githubusercontent.com/22176552/194453627-daf069b2-dc63-4390-b8c6-7f574a3afc98.png">

2022-10-07 05:10 UTC, nbalance97 requested changes
렉스 코드 잘 봤습니다~ 간단한 변경점 하나 제안드릴게요ㅋㅋ

2022-10-07 06:02 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/event/GroupDeleteEvent.java
> +public class GroupDeleteEvent extends ApplicationEvent {
Event는 보면 볼수록 새로운 기능이 많군요! ApplicationEvent의 상속 코드를 삭제했습니다!

2022-10-07 06:03 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/favorite/domain/Favorite.java
> +    private Long memberId;
다른 도메인과 통일성을 갖게 nullable을 추가했습니다

2022-10-07 06:30 UTC, sinb57 requested changes

2022-10-07 06:30 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/favorite/service/FavoriteService.java
> +        if (result) {
변수추출을 하지 않아도 좋아보여요!! 아니면 result 변수명을 바꿔서 의미부여하는 것은 어떤가요?? 음.. `alreadyLiked`???

2022-10-07 06:30 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/favorite/service/FavoriteService.java
> +    }
```suggestion
    @Transactional
    public void cancel(Long groupId, Long memberId) {
        Favorite favorite = favoriteRepository.findByGroupIdAndMemberId(groupId, memberId)
                .orElseThrow(() -> new GroupException(MEMBER_NOT_YET_LIKE));

        favoriteRepository.delete(favorite);
    }
```
이와 같은 리팩토링 어떠신가요??

2022-10-07 06:30 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupValidator.java
> +        if (!result) {
여기도 마찬가지로 result 대신 다른 변수명을 취하는 것이 좋아보여요!! 아니라면 변수추출을 하지않는 것이 좋다고 봐요~ result 변수명만으로는 무엇의 결과를 의미하는지 모르기 때문에 결국 변수의 구현을 봐야했어요!!

2022-10-07 06:30 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/member/service/MemberValidator.java
> +        }
```suggestion
        Member member = memberRepository.findById(memberId)
                .orElseThrow(() -> new MemberException(MemberErrorCode.MEMBER_NOT_EXIST));

        if (member.isDeleted()) {
            throw new MemberException(MemberErrorCode.MEMBER_NOT_EXIST);
        }
```
`회원이 존재하지 않음`과 `삭제되었음`은 관심사가 다르기 때문에 예외 throw를 달리두는 것이 좋아보여요!!

2022-10-07 06:30 UTC, sinb57 commented on backend/src/test/java/com/woowacourse/momo/favorite/domain/FavoriteRepositoryTest.java
> +    private FavoriteRepository favoriteRepository;
```java
@TestConstructor(autowireMode = TestConstructor.AutowireMode.ALL)
@RequiredArgsConstructor
```
클래스에 위 어노테이션을 지정해서, `@Autowired`를 지우는 것은 어떤가요?? (MemberValidatorTest 참고!!)

2022-10-07 06:40 UTC, Seongwon97 commented on backend/src/test/java/com/woowacourse/momo/favorite/domain/FavoriteRepositoryTest.java
> +    private FavoriteRepository favoriteRepository;
피드백을 반영하여 수정하였습니다!

2022-10-07 06:43 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/member/service/MemberValidator.java
> +        }
해당 피드백도 반영하였습니다!

2022-10-07 06:46 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupValidator.java
> +        if (!result) {
result를 isExist변수로 네이밍을 수정하였습니다!

2022-10-07 06:54 UTC, nbalance97 approved these changes
고생하셨습니다~~

2022-10-07 07:06 UTC, sinb57 approved these changes
리뷰 반영 잘 봣습니다~!!! 어푸어푸!!!

2022-10-07 07:07 UTC, merged