[BE] 동일한 사용자 이름으로 회원가입하는 경우에 대한 유효성 검증
woowacourse-teams/2022-momo pull request #437
Opened 2022-10-07 09:03 UTC by sinb57

🚀 기능 추가 설명
- https://github.com/woowacourse-teams/2022-momo/issues/414
- 위의 PR에서 반영했던 `사용자 아이디 Unique 적용`에 대해 유효성 검증 로직을 추가

2022-10-08 06:21 UTC, Seongwon97 requested changes
이프 수고많으셨습니다!
몇가지 피드백을 남겼으니 확인 부탁드릴게요🚀

2022-10-08 06:21 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/auth/exception/AuthErrorCode.java
> +    SIGNUP_USER_NAME_DUPLICATED(400, "SIGNUP_003", "이미 가입된 이름입니다."),
두 에러 코드의 번호가 003으로 같은 상황인데 004와 같이 다른 번호를 넘겨주는게 좋을 것 같습니다!

2022-10-08 06:21 UTC, Seongwon97 commented on backend/src/test/java/com/woowacourse/momo/favorite/controller/FavoriteControllerTest.java
> +        SignUpRequest request = new SignUpRequest(userId, "wooteco1!", userId);
중복된 userName으로 가입이 불가능하여 직접 지정한 이름을 변경하신 것 같은데, 변경하신다면 userId를 다른 이름으로 변경하던가 아니면 userName도 외부에서 주입받도록 하는 것이 좋을 것 같습니다! 

저는 userId, userName을 한 가지 단어로 표현할 수 있는 단어가 떠오르지 않아서..`Long saveMember(String userId, String userName)`과 같이 두 이름을 받는게 좋을 것 같기도 합니다

2022-10-08 06:21 UTC, Seongwon97 commented on backend/src/test/java/com/woowacourse/momo/group/controller/ParticipateControllerTest.java
>          return memberService.signUp(request);
해당 부분도 위의 코멘트와 같습니다!

2022-10-09 06:52 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/auth/exception/AuthErrorCode.java
> +    SIGNUP_USER_NAME_DUPLICATED(400, "SIGNUP_003", "이미 가입된 이름입니다."),
앗! 좋습니다~

2022-10-09 07:46 UTC, sinb57 commented
렉스 리뷰 반영하면서 추가적으로 진행한 사항은 다음과 같습니다~!!!
signUp 로직이 Auth 패키지에서 Member 패키지로 이동했는데
Member 에 배치된 signUp 로직에서 여전히 Auth 패키지에 존재하는 Exception과 ErrorCode를 사용하고 있는 점과
관련 테스트 코드가 Member 패키지가 아닌 Auth 패키지에 위치하고 있는 점
위와 같은 사항을 의존성을 고려하여 Member 패키지에 배치하도록 수정 반영했습니다~!!~!~!~!~!!

2022-10-10 13:01 UTC, kyukong approved these changes
빠트렸던 부분 빠르게 추가해주셔서 감사해요 😅 바로 approve 할게요!

2022-10-10 13:01 UTC, kyukong commented on backend/src/test/java/com/woowacourse/momo/member/service/MemberServiceTest.java
> +        private static final String USER_NAME = "모모";
깔끔하니 좋네요 👍

2022-10-11 00:57 UTC, nbalance97 approved these changes
이프 고생하셨습니다ㅎㅎ 아주아주 간단한 리뷰 남겨드렸습니다~

2022-10-11 00:57 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/member/service/MemberService.java
> +        validateUserNameNotDuplicated(userName);
소소한건데.. 위엔 is가 붙어있는데 아래는 붙어있지 않네요ㅎㅎ

2022-10-11 01:14 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/member/service/MemberService.java
> +        validateUserNameNotDuplicated(userName);
예리하시네요ㅋㅎㅎ 반영했습니다~

2022-10-11 01:15 UTC, Seongwon97 approved these changes
수고하셨습니다!

2022-10-11 01:15 UTC, merged