[BE] 이미지 기능 구현
woowacourse-teams/2022-momo pull request #462
Opened 2022-10-14 09:12 UTC by kyukong

## ✨ Issue
- #327 

## 🚀 구현한 기능
이미지에 관련된 전반적인 기능을 구현하였습니다.

### 모임(Group)
- `모임 조회` 시 모임의 이미지 접근 URL 도 포함하여 응답한다.
  - 모임 단일 조회, 모임 목록 조회, 모임 검색 조회 등 모두 포함
- `모임 생성` 시 DB 에 기본 이미지 정보를 저장한다.
  - GroupCreateEvent, GroupImageCreateEventListener 이용
- `모임 삭제` 시 DB 에 저장된 이미지 정보를 삭제한다
  - GroupDeleteEvent, GroupImageDeleteEventListener 이용
- `모임 이미지 저장` 시 DB 에 저장된 이미지 정보를 수정하고 이미지 서버에 이미지를 저장한다.
  - ImageConnector 참고
- `모임 이미지 초기화` 시 DB 에 저장된 이미지 정보를 기본 이미지 정보로 수정한다.

### 카테고리(Category)
- `카테고리 조회` 시 아이콘 접근 URL 도 포함하여 응답한다.

## ✓ 추후 해야할 일
- 모임 기본 이미지 서버에 저장
- 카테고리 아이콘 서버에 저장

2022-10-17 05:43 UTC, Seongwon97 requested changes
안녕하세요 유콩~
이미지 기능 구현 코드 잘 봤습니다!!
많은 노력을 해주셨다는게 코드에서도 보이네요👍

몇가지 코멘트를 남겼으니 확인 부탁드립니다!

2022-10-17 05:43 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/group/domain/search/dto/GroupSummaryRepositoryResponse.java
> +@Setter
필드 위에 `@Setter`를 붙일 경우 해당 필드에 대한 setter가 열릴거에요!

2022-10-17 05:43 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/storage/controller/GroupImageController.java
> +            @PathVariable Long groupId, @AuthenticationPrincipal Long memberId, MultipartFile multipartFile
프로젝트 코드를 보면 전반적으로 memberId를 먼저 받은 후, groupId를 받고 있습니다! 
해당 부분도 memberId를 먼저 받도록 수정하는건 어떨까요?

2022-10-17 05:43 UTC, Seongwon97 commented on backend/src/test/java/com/woowacourse/momo/storage/controller/GroupImageControllerTest.java
> +                )
66~67번 라인과 90번 라인을 비교했을 때 andExpect를 하기 전 `)`에서 줄바꿈을 유무의 차이가 있는 것 같아요.
한 개의 클래스 파일 안에 있는 메서드들인 만큼 통일감을 주면 좋을 것 같습니다.

2022-10-17 06:44 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/category/domain/Category.java
> +    private final String iconName;
프론트의 요청을 추가한 부분인데요! 모모 사이트 들어가면 카테고리의 이미지가 버튼에 적용되어 있습니다. '이미지' 라는 용어가 겹칠거같아 아이콘으로 해두었습니당 다른 좋은 의견 있으면 알려주세요~
![image](https://user-images.githubusercontent.com/92148749/196107007-95fe4d7c-4393-4f14-902d-2ccc319a7d19.png)

2022-10-17 06:46 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/domain/search/dto/GroupSummaryRepositoryResponse.java
> +@Setter
앗 그러게요 필요한 것만 열어도 되겠네요 감사합니다 😄

2022-10-17 06:49 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/storage/domain/GroupImage.java
> +    @Column
JPA 에서 제공하는 설정에 대해서 생략 가능하더라도 명시적으로 적어두자~ 라는게 저희 팀 규약이라고 생각했습니다 😅

```java
@Column(name = "group_id", nullable = false)
private Long groupId;
```

위의 코드에서 `@Column` 의 `name` 을 생략해도 되지만 추가한 것처럼요! `@Column` 어노테이션을 생략하는 편이 좋을까요?

2022-10-17 07:00 UTC, nbalance97 approved these changes
유콩 고생 많으셨습니다~

간단한 리뷰 몇가지 남겨 드렸으니 확인 부탁드릴게욯ㅎㅎ

2022-10-17 07:00 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/storage/service/GroupImageService.java
> +    }
이부분 개인적으로 주석이 필요할 거 같아요.. 이해가 조금 어렵네요^^..

2022-10-17 07:05 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/category/domain/Category.java
> +    ETC(10, "기타", "etc.jpg", "etc.png");
각각 모임을 생성할 때 설정되는 기본 이미지와 카테고리의 아이콘을 나타내는 정보인데요, 통일해도 괜찮을까요? 이름을 동일하게 했던건 이름을 별도로 짓기 귀찮아서..였는데요.. 이름이 완전히 동일하면 헷갈릴 수 있지 않을까요?

2022-10-17 07:07 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupSearchService.java
> +
`convertImageUrl` 로 바꾸어 보았습니다~

2022-10-17 07:25 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/storage/service/GroupImageService.java
> +    }
주석 추가하면서 변수도 추출하였습니다~

2022-10-17 08:04 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/storage/domain/GroupImageRepository.java
> +    Optional<String> findImageNameByGroupId(@Param("groupId") Long groupId);
리팩토링 전 GroupImage 에는 Group 이 있어서 혹시나! 하고 JPQL 을 써봤습니다~(현재는 groupId 를 가집니다) 그런데 로직들을 보니 GroupImage 가 Group 없이 독단적으로 쓰이는 곳이 없군요;; 말씀하신대로 바꾸었습니다~

2022-10-18 02:29 UTC, sinb57 requested changes
잘봤습니다!! 아프신데도 기능 구현하셔서 PR 날리는 모습을 보니, 우리도 더더욱 열심히해야겠다는 마음이 생기네요! Changed Files가 많아서 피드백 또한 많은데요. 천천히 확인부탁드려요

2022-10-18 02:29 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/category/domain/Category.java
> +    ETC(10, "기타", "etc.jpg", "etc.png");
확장자를 달리해서 구분을 짓는다면, 어떤 것이 썸네일이고 어떤 것이 아이콘인지 명확해보이지 않아요
확장자 통일에 대해서는 잘 모르겠지만, 파일명은 변경할 필요가 있다고 생각됩니다 `study_thumnail.jpg` `study_icon.png`

2022-10-18 02:29 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/category/domain/Category.java
> +    }
```suggestion
    public boolean isDefaultImage(String imageName) {
        return defaultImageName.equals(imageName);
    }
```
카테고리 하나에 대해 특정지어 defaultImage 일치여부를 확인한다면 위와 같이 로직이 변경되어야 하지 않을까요?

2022-10-18 02:29 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupModifyService.java
> +        applicationEventPublisher.publishEvent(new GroupCreateEvent(group.getId(), group.getCategory()));
이벤트 활용 👍👍👍

2022-10-18 02:29 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/group/service/GroupSearchService.java
> +        String imageName = groupImage.getImageName();
```suggestion
        String imageName = groupImageRepository.findByGroupId(group.getId())
                .map(GroupImage::getImageName)
                .orElse(group.getCategory().getDefaultImageName());
```
다음과 같이 리팩토링하면 깔끔할 것 같아요!!

2022-10-18 02:29 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/storage/service/GroupImageService.java
> +        return fullPathOfSavedImage.substring(startIndexImageName);
```suggestion
        int startIndexOfImageName = fullPathOfSavedImage.lastIndexOf('/') + 1;
        return fullPathOfSavedImage.substring(startIndexOfImageName);
```

2022-10-18 02:29 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/storage/service/GroupImageService.java
> +        return fullPathOfSavedImage.substring(startIndexImageName);
파일 이름만 반환할 것이라면, '/' 기준으로 마지막 element를 반환하도록 로직을 구성하는 쪽이 훨씬 좋아보여요

2022-10-18 02:29 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/storage/support/ImageConnector.java
> +            Path tempFile = Files.createTempFile(filename, extension);
sonarqube에서 위험한 코드라고 탐지하고 있어요!! 확인부탁드려요

2022-10-18 02:39 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/storage/domain/GroupImage.java
> +    @Column
```java
    @Column(name = "image_name")
    private String imageName;
```
@Column 에 name 값을 추가하여 통일감을 맞췄습니다~!

2022-10-18 04:28 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/category/domain/Category.java
> +    }
그렇네요 ㅎㅎㅎㅎㅎ 감사해요 😅

2022-10-18 04:46 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/storage/event/GroupImageCreateEventListener.java
> +    }
오홍~ 좋네요!! 바로 반영했습니다~!

2022-10-18 05:26 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/storage/event/GroupImageDeleteEventListener.java
> +public class GroupImageDeleteEventListener {
그룹이 생성되었을 때 그룹 이미지를 `생성` 시키는 로직과, 그룹이 삭제되었을 때 그룹 이미지를 `삭제` 하는 로직이 있어 로직 병합 후 GroupImageEventListener 로 이름을 변경하였습니다~

2022-10-18 05:32 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/storage/support/ImageConnector.java
> +        String extension = filename.substring(filename.lastIndexOf("."));
이것 포함해서 Controller 계층에서의 null 처리도 추가하였습니다~!

2022-10-18 06:46 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/category/domain/Category.java
> +    private final String iconName;
아이콘은 `icon_` 을 붙이고 모임 썸네일은 `thumbnail_` 을 붙여서 구분했습니다!

2022-10-18 08:10 UTC, Seongwon97 approved these changes
수고하셨습니다 유콩👍
RestDocs변경보다 늦게 머지된다면 설정 값만 올바르게 변경 부탁드릴게요!

2022-10-18 08:22 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/storage/controller/GroupImageController.java
> +                                       @AuthenticationPrincipal Long memberId, @NotNull MultipartFile multipartFile) {
엥 변경한 줄 알았는데 왜 돌아왔지... 반영했습니다!!

2022-10-18 08:24 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/storage/domain/GroupImage.java
> +    @Column(name = "image_name")
그러게요.. DB 의 테이블명 및 컬럼명은 **스네이크 케이스**를 사용한다는데 지금처럼 변경해주는것은 어떨까요?

2022-10-18 08:43 UTC, nbalance97 approved these changes
변경사항 확인했습니다 유콩~ 고생하셨습니다!

2022-10-19 03:12 UTC, sinb57 approved these changes
변경점 잘 확인했습니다~~

2022-10-19 03:31 UTC, merged