[BE] 찜하기 데이터 삭제 관련 이벤트 처리방식을 비동기로 변경
woowacourse-teams/2022-momo pull request #549
Opened 2022-12-18 18:56 UTC by Seongwon97

## ✨ Issue
- #548

## 🥇 구현한 기능
이벤트 처리 방식을 동기 -> 비동기로 수정

## 🧾 상세 내용
작업 관련 상세 내용은 아래의 블로그 게시글에 기록해뒀습니다.

📌 [모모팀 서비스 성능 개선기4 (비동기 처리를 통한 장애 전파 제거)](https://seongwon.dev/Spring/20221218-%EB%AA%A8%EB%AA%A8%ED%8C%80-%EC%84%9C%EB%B9%84%EC%8A%A4%EC%84%B1%EB%8A%A5-%EA%B0%9C%EC%84%A0%EA%B8%B04/)

2022-12-18 20:55 UTC, sinb57 requested changes
렉스~ 비동기처리라니!! 재밌는 PR이군요ㅋㅎㅎ 리뷰 확인부탁드려요

2022-12-18 20:55 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/favorite/event/FavoriteDeleteEventListener.java
> +@Transactional
`@Transactional` 어노테이션이 필요한가요???

2022-12-18 20:55 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/favorite/event/FavoriteDeleteEventListener.java
> +    @Async
현재 외래키로 엮여 있어서 곧바로 비동기처리하면 예외가 발생하지 않을까 걱정됩니다. 
`MemberService#deleteById`와 `GroupModifyService#delete` 메서드 내 이벤트 발행 로직 순서랑 함께 고려하면 좋을 것 같아요

2022-12-18 20:55 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/global/config/AsyncConfiguration.java
> +public class AsyncConfiguration {
`MomoApplication`에 `@EnableAsync`를 달지않고 별도의 Configuration 클래스로 분리한 이유가 있으신가요?? `MomoApplication`에 바로 달아놓는게 파악하기 좋을것 같아여

2022-12-19 00:55 UTC, nbalance97 requested changes
비동기 적용 좋네요!! 블로그에 정리해둔 글도 잘 봤습니다 😀

2022-12-19 00:55 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/favorite/event/FavoriteDeleteEventListener.java
> +    @Async
문득 든 생각인데, 사용자 관점에서
모임 삭제 -> 커밋 이후 ```favoriteRepository.deleteAllByGroupId(event.getId());```가 실행되지 않는다면 유령 데이터가 남아있을텐데, 사용자가 요청할 때 유령 데이터는 넘겨주면 안되지 않을까요?

아니면 이부분에 대해서 유령 데이터인지 db에 직접 조회해보는 방법도 필요할 것 같아요. 그렇게 된다면 조회 성능이 많이 떨어질 거 같고,, 차라리 EventListener로 묶는게 나을지도 모를거 같습니다😂 

아래의 deleteMember의 경우는 괜찮습니다! 유저가 삭제되었을 때는 찜한 모임을 애초에 조회할 수가 없을거 같아요!!

2022-12-19 06:09 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/favorite/event/FavoriteDeleteEventListener.java
> +@Transactional
비동기로 처리하게된다면 이벤트를 Publish한 스레드와 다른 스레드에서 동작하게 됩니다.
그런 이유때문에 `@Transactional` 어노테이션이 없다면 이벤트를 처리하는 메서드는 트랜잭션이 없는 상태에서 실행되게되는데 로직이 Repository를 접근하는 로직이라 트랜잭션이 없으면 `javax.persistence.TransactionRequiredException`예외가 터지게 됩니다ㅠ

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/57744251/208354500-8f9cff4f-4e34-4cf7-83da-810152766c66.png">

2022-12-19 06:09 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/favorite/event/FavoriteDeleteEventListener.java
> +    @Async
@nbalance97 
현재 찜한 모임 조회 로직의 모임 id를 가져오기 위한 쿼리를 살펴보면 Group을 기준으로 innerJoin을 통해 Favoriter테이블과 조인을 하고 있습니다! outerJoin이 아닌 innerJoin이라 해당 부분에 대해서는 사용자가 찜한 모임 조회요청을 한다하여도 유령 데이터가 넘어가는 일은 없을 것으로 판단됩니다!
```java
    private List<Long> findLikedGroupIds(SearchCondition condition, Long memberId, Pageable pageable) {
        return queryFactory
                .select(group.id)
                .from(group)
                .innerJoin(favorite).on(group.id.eq(favorite.groupId))
                .where(
                        favorite.memberId.eq(memberId),
                        conditionFilter.filterByCondition(condition)
                )
                .orderBy(orderByDeadlineAsc(condition.orderByDeadline()).toArray(OrderSpecifier[]::new))
                .offset(pageable.getOffset())
                .limit(pageable.getPageSize())
                .fetch();
    }
```

2022-12-19 06:15 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/favorite/event/FavoriteDeleteEventListener.java
> +    @Async
@sinb57 
헉..DB의 FK가 있어 해당 부분에 대해서 문제가 발생하는군요... 
MemberService#deleteById와 GroupModifyService#delete 의 로직 순서를 찜하기 데이터를 먼저 삭제하는 방식으로 순서 변경을 하더라도 결국 찜하기 데이터 삭제 중 오류가 발생하면 회원탈퇴 또는 모임 삭제는 FK에 의해 수행되지 않게됩니다..
이 부분에 대해서는 현재 이슈의 목적(장애 전파 해결)을 달성하려면 FK를 제거하는 방법밖에 없는 것 같습니다😭

2022-12-19 06:25 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/global/config/AsyncConfiguration.java
> +public class AsyncConfiguration {
해당 부분에 대해서는 일전에 Spring 공식문서에서 슬라이스 테스트를 위해서는 `@SpringBootApplication`이 붙은 클래스와 `@EnableAsync`와 같은 부가적인 설정은 분리하는 것이 좋다는 글을 보고 분리하는 방식으로 진행하였습니다.

https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.testing.spring-boot-applications.user-configuration-and-slicing

2022-12-19 06:27 UTC, Seongwon97 commented
피드백에 대한 저의 의견을 남겼으며 추가로 비동기 처리를 동작하는 스레드를 매번 생성하는 것이 아닌 스레드풀을 통해 재사용을 하도록 개선을 해봤습니다! 

자세한 내용은 아래의 블로그에 추가로 남겨뒀습니다!

📌 [모모팀 서비스 성능 개선기4 (비동기 처리를 통한 장애 전파 제거)](https://seongwon.dev/Spring/20221218-%EB%AA%A8%EB%AA%A8%ED%8C%80-%EC%84%9C%EB%B9%84%EC%8A%A4%EC%84%B1%EB%8A%A5-%EA%B0%9C%EC%84%A0%EA%B8%B04/)

2022-12-19 14:35 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/favorite/event/FavoriteDeleteEventListener.java
> +    @Async
말씀해주신 대로 현재 조회로직에서는 문제가 없네요ㅎㅎ 하지만 favorite 테이블은 반드시 Inner Join과 함께 사용해야 한다는 제약조건이 생기게 될 거 같습니다. 또한 앞에서의 커멘트대로 db상에서 사용되지 않는 데이터가 누적될 일도 있고, 추후 삭제하기 위해 사용되지 않는 찜 데이터를 찾는것도 일이 될 거 같습니다!

이러한 데이터 불일치 문제 때문에 쉽게 건드리지 못한 부분이기도 해요..

2022-12-21 19:16 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/favorite/event/FavoriteDeleteEventListener.java
> +    @Async
@Seongwon97  저 또한 FK를 제거하는 것 말고 방법을 생각하지 못하겠군요ㅠ

2022-12-21 19:17 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/global/config/AsyncConfiguration.java
> +public class AsyncConfiguration {
아하! 테스트 환경 격리를 위해서라면 찬성합니다~!

2022-12-21 19:26 UTC, sinb57 requested changes
렉스~ 확인이 늦어 죄송합니다!
블로그글 재밌게 잘 읽었구요. 추가하신 스레드풀 설정도 확인했습니다~

궁금한 점 적어두었으니 확인부탁드릴게요!!

앞서 드렸던 질문에 대해서는
FK를 지우는 방향으로 정하셨다면, Conversation을 resolve하셔도 좋습니다~

2022-12-21 19:26 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/global/config/AsyncConfiguration.java
> +        threadPoolTaskExecutor.setMaxPoolSize(4);
스레드풀!! 좋은 접근이네요~
개인적인 생각으로 '4' 값을 프로퍼티 설정파일에서 관리하는 것은 어떨까요?
Tomcat 스레드풀 설정이랑 깊은 연관이 있을 것이라 생각되어서 동일한 설정파일에서 관리되면 좋을 것 같아요

그리고 `CorePoolSize`와 `MaxPoolSize`를 동일하게 4로 지정하신 이유가 있으신가요?

2022-12-22 13:29 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/favorite/event/FavoriteDeleteEventListener.java
> +    @Async
음..제 개인적인 생각으로는 `메인동작(모임 삭제)`를 실행함에 있어 `부가기능의 동작(찜하기 데이터 삭제)`는 `장애 전파`와 `유령 데이터의 발생가능성` 중 하나는 포기해야하는 Trade-off한 관계라 생각해요..

많은 기업들이 MSA아키텍처를 도입하며 모듈 별로 서비스와 DB를 분리하는 것도 이와 같이 장애의 전파를 최소화의 이점을 얻고자 유령 데이터의 발생 가능성을 열어두는 문제를 감수한다 생각해요. 서비스를 제공하는 입장에서 이러한 선택을 하는 것은 사용자 경험을 생각했을 때, 사용자가 서비스를 사용하며 장애를 경험할 확률을 가능하다면 최소화하기 위해서가 아닌가?라고 생각합니다.

비동기로 이벤트처리를 한다면 `EventListener`대신에 `TransactionalEventListener`를 사용하는 것은 맞다고 생각합니다. 비동기로 처리되어 둘은 다른 스레드에서 실행될텐데 `TransactionalEventListener`를 통해 Commit이후에 이벤트 처리를 실행하도록 구현하지 않는다면 아래의 상황이 발생할 수 있을 것 같아요.
1. 사용자가 회원 탈퇴를 시도했다.
2. 찜하기 데이터의 삭제는 성공하였는데 회원 삭제가 실패한 상황이 발생하여, 사용자에게는 회원 탈퇴가 실패했다는 피드백을 받았다. 
3. 사용자는 탈퇴 계획을 중단하고 마음을 바꿔 서비스를 다시 이용하려고 마음먹었다.
4. 서비스를 이용하려고 보니 이전에 찜한 데이터가 모두 사라져있는 상황을 경험하였다.

2022-12-22 15:15 UTC, nbalance97 commented on backend/src/main/java/com/woowacourse/momo/favorite/event/FavoriteDeleteEventListener.java
> +    @Async
@Seongwon97 저도 트레이드 오프 관계라고 생각합니다! 하지만 이번 비동기 이벤트 처리 로직에서는 정말로 개선이 되었는가에 대해서 의문이 들어요.

개인적인 생각으로는 비동기 처리의 경우는 이벤트를 받은 메소드 측에서 비교적 오랜 시간 작업(외부 API를 호출하는 등의 네트워크 작업)을 하는 경우에는 비동기로 처리하는 것이 성능이 확실히 향상되므로 비동기를 고민해 보는 것이 맞다고 생각합니다.
이번 PR에서는 이벤트를 수신하는 측에서의 작업이 비교적 간단한 작업이라고 생각하였습니다. 간단한 작업이었기에 비동기까지 도입하여 유령 데이터의 여지를 남기는 것이 맞나..? 싶은 생각이 들기는 합니다..ㅎㅎ 오히려 동기로 처리하였을 때는 버그가 없었기 때문이고 생각해 보았을 때 성능적으로도 큰 차이는 없을 거 같기 때문이었습니다.

비동기 vs 동기 성능 테스트 이후에 눈에 띈 성능 향상이 아니라면 버그의 여지를 남기는 것 보다는, 동기가 더 낫지 않을까 하는 개인적인 의견이었습니다ㅎㅎ 렉스의 의견도 맞다고 생각하기 때문에 도입하셔도 좋습니다~

참고로 아래 EventListener 이야기는 비동기는 아니고.. 동기로 처리했을 때를 이야기한 부분이었습니다!

2022-12-22 15:19 UTC, nbalance97 approved these changes
저는 이만 Approve 하겠습니다~ 고생하셨습니다 렉스!!

2022-12-26 04:15 UTC, Seongwon97 commented on backend/src/main/java/com/woowacourse/momo/global/config/AsyncConfiguration.java
> +        threadPoolTaskExecutor.setMaxPoolSize(4);
답변이 늦었네요ㅠㅠ
`CorePoolSize`는 동시에 실행시킬 스레드의 개수를 의미하고 `MaxPoolSize`는 이름에서 알 수 있듯이 최대 풀 사이즈를 의미합니다.

`CorePoolSize`의 경우 과거 Core가 2개인 EC2의 환경을 고려하였을 때, ContextSwitch까지 고려하여 core*2의 수로 정하였고 `MaxPoolSize`의 경우도 동일하게 설정하였습니다.
흠..그런데 생각을 해보니 `MaxPoolSize`의 경우 값을 8정도로 더 올려도 되지 않을까?하는 생각도 드네요..!

그리고 혹시 Tomcat 스레드풀 설정 파일의 위치가 어디인지 알려주실 수 있나요..? yml파일을 다 찾아보는데 해당 값은 찾지 못하겠네요ㅠㅠ

2022-12-26 05:30 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/global/config/AsyncConfiguration.java
> +        threadPoolTaskExecutor.setMaxPoolSize(4);
어라...? 성능테스트 당시에 톰캣 thread개수나 accept-count 지정하지 않았었나요???
```
# 예시
server:
  tomcat:
    threads:
      max: 200 # 생성할 수 있는 thread의 총 개수
      min-spare: 10 # 항상 활성화 되어있는(idle) thread의 개수
    max-connections: 8192 # 수립가능한 connection의 총 개수
    accept-count: 100 # 작업큐의 사이즈
    connection-timeout: 20000 # timeout 판단 기준 시간, 20초
```

2022-12-26 05:31 UTC, sinb57 commented on backend/src/main/java/com/woowacourse/momo/global/config/AsyncConfiguration.java
> +        threadPoolTaskExecutor.setMaxPoolSize(4);
없다니 아쉽군요ㅋㅎㅎ 필수 반영 사항은 아니어서 넘어가겠숨다~

2022-12-26 05:31 UTC, sinb57 approved these changes
렉스~ 고생했숨다 어푸어푸할게요

2023-01-03 09:19 UTC, kyukong approved these changes
안녕하세요 렉스!! 🦖 리뷰가 늦어서 죄송합니다ㅠ.ㅠ

다른 분들이 남겨주신 리뷰도, 렉스가 답변 달아주신 리뷰도 꼼꼼히 읽어봤어요.
다들 좋은 토론 시간을 가진것같아 좋네요. ㅎㅎ
다만, 비동기 처리를 도입함으로써 어쩔 수 없는 부분이 생겨났는데 (불필요한 데이터 축적 가능성)
아직은 어떻게 해결하는 것이 좋을지 .. 잘 모르겠네요 🥺
크게 문제되는 부분은 아니기 때문에 approve 진행합니다!

2023-01-03 09:19 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/favorite/event/FavoriteDeleteEventListener.java
> +    @Async
라쿤이 말씀해주신 것처럼, 동기나 비동기나 현재 상황에서 큰 차이는 없어 보여요. 비동기를 적용함으로써 실행 속도의 이점도 크지는 않고, 반대로 쓰레기 데이터(어감이 좀...^^;;) 가 남는 양도 큰 영향을 미치지 않을 것처럼 보입니다. 렉스가 말씀해주신 것처럼 inner join 을 거쳐야 한다는 점도 있고 사용자의 수를 감안했을 때.. 남더라도 영향이 매우 적을것 같네요... 😅 그래도 덕분에 이벤트 비동기 방식에 대해 찾아보면서 배울 수 있는 시간이 있었기 때문에 의미있었던 과정이라고 생각합니다. ㅎㅎ

2023-01-03 09:19 UTC, kyukong commented on backend/src/main/java/com/woowacourse/momo/global/config/AsyncConfiguration.java
> +        threadPoolTaskExecutor.setMaxPoolSize(4);
그 당시 설정이 필수는 아니었기 때문에 따로 설정하지는 않았었습니다.. ㅎㅎ

2023-01-04 13:14 UTC, merged